/* SM1 pure predicates. Local Reference owns normalization; no fetch or map access. */
(function(root,factory){const api=factory(typeof module==='object'?require('./brim_local_reference_filter_engine.js'):root.BRIM.localReferenceFilterEngine,typeof module==='object'?require('./soil_moisture_depths.js'):root.BRIM.soilMoistureDepths);if(typeof module==='object')module.exports=api;else root.BRIM.soilMoistureEngine=api;})(typeof window==='object'?window:this,function(LR,D){
'use strict';
const clone=x=>structuredClone(x);
const normalize=x=>LR.normalizeSearch(String(x??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,''));
const defaults=()=>({query:'',min:null,max:null,age:null,onBLM:false,distance:null,depth:'site',rule:'display',depths:[],selection:'default',lower:0,upper:null,includeUnknown:false,choices:{}});
function validated(d){const n=Object.assign(defaults(),clone(d));if(!['default','range','nominal','exact'].includes(n.selection))throw Error('Invalid depth selection');if(['range','nominal'].includes(n.selection)){if(!Number.isFinite(n.lower)||n.lower<0||n.upper!==null&&(!Number.isFinite(n.upper)||n.upper<n.lower))throw Error('Invalid depth interval');n.depth='site';n.rule='display';n.depths=[];}for(const key of ['min','max','age','distance']){if(n[key]===''||n[key]===null)n[key]=null;else if(!['number','string'].includes(typeof n[key])||!Number.isFinite(Number(n[key])))throw Error('Enter finite '+key);else n[key]=Number(n[key]);}if(n.min!==null&&n.max!==null&&n.min>n.max)throw Error('Minimum exceeds maximum');if(n.age!==null&&n.age<0||n.distance!==null&&n.distance<0)throw Error('Age/distance must be nonnegative');if(!['display','any','every'].includes(n.rule))throw Error('Depth rule invalid');if(n.rule!=='display'&&!n.depths.length)throw Error('Choose at least one exact depth');if(!['site','unknown'].includes(n.depth)&&(!Number.isFinite(Number(n.depth))||Number(n.depth)<0))throw Error('Invalid depth');if(n.depths.some(x=>x!==null&&(!Number.isFinite(x)||x<0)))throw Error('Invalid exact depth');return n;}
function primary(st,depth){let all=st.sensors.filter(s=>s.parameter==='soil_moisture');if(depth==='site')return all.find(s=>s.id===st.primary_sensor)||null;all=all.filter(s=>depth==='unknown'?s.depth_mm===null:s.depth_mm===Number(depth));if(st.requires_explicit_sensor)return all.length===1?all[0]:null;return all.sort((a,b)=>(a.primary_rank??999)-(b.primary_rank??999)||a.id.localeCompare(b.id))[0]||null;}
function age(s,now){if(!s?.observation?.date)return null;const t=Date.parse(s.observation.date+'T00:00:00'+(s.observation.day_offset||'+00:00'));return Number.isFinite(t)?Math.max(0,Math.floor((now-t)/86400000)):null;}
// Current prepared products declare normalized percent VWC explicitly. This
// adapter is the eligibility boundary; never infer fraction/percent from value.
// A later fixed producer contract can supply its resolved value here.
function percentVwc(s){const o=s?.observation;return s?.parameter==='soil_moisture'&&s.unit==='percent VWC'&&s.capabilities?.latest_vwc===true&&o?.eligible===true&&Number.isFinite(o.value)&&o.value>=0&&o.value<=100?o.value:null;}
function qualifies(s,c,now){const o=s?.observation;if(!o||!o.eligible||!Number.isFinite(o.value))return false;const a=age(s,now),v=percentVwc(s),absolute=c.min!==null||c.max!==null;return(!absolute||v!==null&&(c.min===null||v>=c.min)&&(c.max===null||v<=c.max))&&(c.age===null||a!==null&&a<=c.age);}
// No fixed history-sidecar adapter is connected yet. Source popup reference
// science is not a declaration of comparable map Context categories.
function modeCapability(mode){if(mode==='context'||mode==='reference')return{available:false,reason:'Context unavailable: validated source reference capability is not connected.'};return{available:['value','change','availability'].includes(mode),reason:'Unknown map mode'};}
function rank(st,q){if(!q)return 9;const names=[st.id,st.name,...(st.aliases||[])].map(normalize);if(names.includes(q))return 0;if(names.some(n=>n.startsWith(q)))return 1;const text=normalize([st.name,st.id,st.provider,...(st.aliases||[])].join(' '));if(q.split(' ').every(t=>text.includes(t)))return 2;return Infinity;}
// A local catalog without a producer primary can expose matching exact series,
// but cannot silently turn the first match into the displayed station sensor.
function explicitMatch(st,c,now,score){
 const all=st.sensors.filter(s=>s.parameter==='soil_moisture'),at=d=>all.filter(s=>d==='site'||(d==='unknown'?s.depth_mm===null:s.depth_mm===Number(d)));
 const interval=['range','nominal'].includes(c.selection);let groups=interval?[all.filter(s=>D.contains(s,c))]:c.rule==='display'?[at(c.depth)]:c.depths.map(d=>at(d===null?'unknown':d));
 const selected=groups.flat().find(s=>s.id===c.choices?.[st.key]);
 if(!interval&&c.rule==='display'&&selected)groups=[[selected]];
 const matched=groups.map(g=>g.filter(s=>qualifies(s,c,now)));
 const unbounded=!interval&&c.rule==='display'&&c.min===null&&c.max===null&&c.age===null&&groups[0].length>0;
 if(!unbounded&&(c.rule==='every'?matched.some(g=>!g.length):!matched.some(g=>g.length)))return null;
 const matches=[...new Set(matched.flat())],chosen=matches.find(s=>s.id===c.choices?.[st.key]);
 const display=chosen||(unbounded&&selected)||(!interval&&c.depth!=='site'&&c.rule==='display'&&groups[0].length===1?groups[0][0]:null);
 return{station:st,display,matches,score};
}
function match(st,c,now){const score=rank(st,normalize(c.query));if(!Number.isFinite(score))return null;if(c.onBLM&&st.blm?.on_blm_ca!==true)return null;if(c.distance!==null&&(!Number.isFinite(st.blm?.dist_to_blm_mi)||st.blm.dist_to_blm_mi>c.distance))return null;if(st.requires_explicit_sensor)return explicitMatch(st,c,now,score);let display=primary(st,c.depth);let matches=[];if(['range','nominal'].includes(c.selection)){matches=st.sensors.filter(s=>s.parameter==='soil_moisture'&&D.contains(s,c)&&qualifies(s,c,now));if(!matches.length)return null;display=matches.find(s=>s.id===c.choices?.[st.key])||matches.find(s=>s.id===st.primary_sensor)||matches.slice().sort((a,b)=>(a.primary_rank??999)-(b.primary_rank??999)||a.id.localeCompare(b.id))[0];return{station:st,display,matches,score};}const numeric=c.min!==null||c.max!==null||c.age!==null;
if(c.rule==='display'){if(numeric&&!qualifies(display,c,now))return null;if(qualifies(display,c,now))matches=[display];}else{const wanted=c.depths.map(d=>primary(st,d===null?'unknown':d));matches=wanted.filter(s=>qualifies(s,c,now));if(c.rule==='every'?matches.length!==wanted.length:!matches.length)return null;}return{station:st,display,matches,score};}
function create(){const state={draft:defaults(),applied:defaults(),enabled:{scan:false,dendra:false,snotel:false},auto:true,autoZoom:false,mode:'value',window:7,unit:'native',transaction:0};return{state,edit(p){Object.assign(state.draft,clone(p));},apply(){const next=validated(state.draft);state.applied=next;state.transaction++;return next;},setMode(mode){if(!modeCapability(mode).available)return false;state.mode=mode;return true;},enable(key,on){state.enabled[key]=!!on;},reset(){state.draft=defaults();this.apply();},pending(){try{return JSON.stringify(validated(state.draft))!==JSON.stringify(state.applied);}catch{return true;}},results(stations,now=Date.now()){return stations.filter(s=>state.enabled[s.source]).map(s=>match(s,state.applied,now)).filter(Boolean).sort((a,b)=>a.score-b.score||a.station.name.localeCompare(b.station.name)||a.station.key.localeCompare(b.station.key));}};}
function modeValue(s,mode,now=Date.now(),windowDays=7){const capability=modeCapability(mode);if(!capability.available)return{value:null,reason:capability.reason};if(!s)return{value:null,reason:'No exact displayed sensor'};const o=s.observation; if(mode==='availability')return{value:o?.eligible?1:0,reason:o?.eligible?'Available; age '+age(s,now)+' days':o?.missing_reason||'No imported value'};if(mode==='change'){if(!s.capabilities?.recent_change)return{value:null,reason:'Compatible daily mean/change not established'};if(age(s,now)>3)return{value:null,reason:'Stale daily mean'};return{value:s.change?.[String(windowDays)]?.delta??null,reason:s.change?.[String(windowDays)]?.state||'Insufficient coverage'};}return{value:o?.eligible?o.value:null,reason:o?.eligible?o.statistic:o?.missing_reason||'No imported value'};}
return{normalize,defaults,validated,primary,age,percentVwc,qualifies,rank,match,create,modeCapability,modeValue};});
