# ==== build_scan_live_popup_sandbox.r =======================================
## RF058:
##   - Plot A monthly reference band/median now repeats the monthly climatology
##     pattern across the display window instead of following sparse actual
##     monthly rows.
##
## RF055d: split popup latest-depth table Date / Age into separate columns.
## RF055: remove overlapping in-SVG monthly note, clarify A/B POA notes,
##        and force four-line non-wrapping hover labels.
## RF055b: clearer B-note wording: years of data, not "support".
## RF055c: start from RF055b; add monthly context points and depth-colored
##         latest point on the daily envelope plot.
## RF051: distinguish Near Normal from No Context in map symbology and
##        print depth/context QA before BRIM integration.
## RF050: sandbox polish for separate depth control / legend boxes,
##        depth selector marker colors based on live-feed depth context JSON,
##        and official station-page link in the popup footer.
## RF049: sandbox polish after first visual QA: map-depth selector JS fix,
##        clearer plot notes, cleaned SVG labels, POR-aware context text,
##        and short-record handling for daily ribbon context.
## RF048d: full overwrite of sandbox script; removes stray split(.$site_code).
##
## PURPOSE:
##   Build a small, fast Leaflet sandbox for developing BRIM Ops Live SCAN
##   popup/hover/plot design without rebuilding the full BRIM HTML map.
## RF051c: near-normal legend, hollow no-context symbols, and multiline HTML tooltips.
## RF054: POR/POA labeling cleanup, depth-record table column, and lower plot title.
##
## DESIGN:
##   - Reads the hosted-feed files generated by the SCAN live-feed script.
##   - Reads the locally generated historical percentile context from RF043.
##   - Optionally reads the full local daily-history RDS to create a compact
##     recent-record monthly context trace above the main water-year ribbon plot.
##   - Writes a timestamped, standalone HTML file for visual iteration so an
##     open older sandbox is not overwritten.
##
## INPUTS:
##   brim-live-data-feeds/docs/data/scan_soil_moisture_latest.geojson
##   brim-live-data-feeds/docs/data/scan_soil_moisture_current_wy_trace.csv
##   brim-live-data-feeds/docs/data/scan_depth_style.csv
##   brim-live-data-feeds/data/input/scan_sms_waterday_percentiles.csv
##   04_processed_data/rds/scan_sms_daily_history.rds  [optional, for top plot]
##
## OUTPUT:
##   06_output/html/dev/scan_live_popup_sandbox_<timestamp>.html
##
## NOTES:
##   This is intentionally a development sandbox.  It should not be sourced by
##   the final BRIM map builder.  Once the popup design is stable, the relevant
##   HTML/SVG patterns can be migrated into the Ops Live SCAN layer.
## ============================================================================

# ==== 1. Project sanity check ================================================

if (!dir.exists("brim-live-data-feeds") || !dir.exists("05_map_build")) {
  stop(
    "Run this script from the PortaTreasure2 / BRIM project root.\n",
    "Expected folders like brim-live-data-feeds/ and 05_map_build/ were not found."
  )
}

# ==== 2. Packages ============================================================

required_pkgs <- c(
  "dplyr", "tidyr", "purrr", "readr", "jsonlite", "lubridate",
  "tibble", "stringr", "htmltools", "leaflet", "htmlwidgets"
)

missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]

if (length(missing_pkgs) > 0) {
  stop(
    "Missing required R packages: ", paste(missing_pkgs, collapse = ", "),
    "\nInstall them before running the SCAN popup sandbox."
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(readr)
  library(jsonlite)
  library(lubridate)
  library(tibble)
  library(stringr)
  library(htmltools)
  library(leaflet)
  library(htmlwidgets)
})

# ==== 3. Paths and user-facing switches ======================================

SCAN_LATEST_GEOJSON <- file.path(
  "brim-live-data-feeds", "docs", "data", "scan_soil_moisture_latest.geojson"
)

SCAN_CURRENT_WY_TRACE_CSV <- file.path(
  "brim-live-data-feeds", "docs", "data", "scan_soil_moisture_current_wy_trace.csv"
)

SCAN_DEPTH_STYLE_CSV <- file.path(
  "brim-live-data-feeds", "docs", "data", "scan_depth_style.csv"
)

SCAN_PERCENTILES_CSV <- file.path(
  "brim-live-data-feeds", "data", "input", "scan_sms_waterday_percentiles.csv"
)

SCAN_DAILY_HISTORY_RDS <- file.path(
  "04_processed_data", "rds", "scan_sms_daily_history.rds"
)

OUT_DIR <- file.path("06_output", "html", "dev")

RUN_TS <- format(Sys.time(), "%Y%m%d_%H%M%S")
OUT_HTML <- file.path(OUT_DIR, paste0("scan_live_popup_sandbox_", RUN_TS, ".html"))

## Default depth for map symbolization and the initially active popup tab.
PLOT_DEPTH_IN <- suppressWarnings(as.integer(Sys.getenv("SCAN_SANDBOX_PLOT_DEPTH_IN", unset = "8")))
if (is.na(PLOT_DEPTH_IN)) PLOT_DEPTH_IN <- 8L

## Keep the plot compact enough for real BRIM popups while still legible.
SVG_WIDTH  <- 600L
SVG_HEIGHT <- 350L

## Top context trace window.  This is intentionally recent-record context, not
## a full POR spaghetti plot.  Ten years is a good first visual compromise.
CONTEXT_YEARS_BACK <- suppressWarnings(as.integer(Sys.getenv("SCAN_SANDBOX_CONTEXT_YEARS", unset = "10")))
if (is.na(CONTEXT_YEARS_BACK) || CONTEXT_YEARS_BACK < 3) CONTEXT_YEARS_BACK <- 10L

## Show station historical monthly reference statistics only when there is
## enough station history to make the trace meaningfully climatological.  The
## actual recent/available monthly trace is still shown even for newer stations.
CONTEXT_STAT_MIN_YEARS <- suppressWarnings(as.integer(Sys.getenv("SCAN_SANDBOX_CONTEXT_STAT_MIN_YEARS", unset = "15")))
if (is.na(CONTEXT_STAT_MIN_YEARS) || CONTEXT_STAT_MIN_YEARS < 5) CONTEXT_STAT_MIN_YEARS <- 15L

## Daily percentile ribbons need less record than the upper monthly context
## reference, but should still be hidden for very new stations.
DAILY_RIBBON_MIN_YEARS <- suppressWarnings(as.integer(Sys.getenv("SCAN_SANDBOX_DAILY_RIBBON_MIN_YEARS", unset = "5")))
if (is.na(DAILY_RIBBON_MIN_YEARS) || DAILY_RIBBON_MIN_YEARS < 3) DAILY_RIBBON_MIN_YEARS <- 5L

# ==== 4. Small helpers =======================================================

pt_chr <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x == "" | is.na(x) | toupper(x) %in% c("NA", "NULL", "NAN")] <- NA_character_
  x
}

pt_num <- function(x) {
  suppressWarnings(as.numeric(gsub(",", "", as.character(x))))
}

pt_esc <- function(x) {
  htmltools::htmlEscape(as.character(x))
}

pt_fmt_num <- function(x, digits = 1, suffix = "") {
  x <- suppressWarnings(as.numeric(x))
  out <- rep("NA", length(x))
  ok <- !is.na(x)
  out[ok] <- paste0(formatC(x[ok], format = "f", digits = digits, big.mark = ","), suffix)
  out <- sub("(\\.\\d*?)0+([^0-9]|$)", "\\1\\2", out)
  out <- sub("\\.([^0-9]|$)", "\\1", out)
  out
}

pt_local_path_check <- function(path, label) {
  if (!file.exists(path)) {
    stop("Missing ", label, ": ", path)
  }
}

pt_svg_line <- function(df, x_col, y_col, xf, yf) {
  df <- df |> dplyr::filter(!is.na(.data[[x_col]]), !is.na(.data[[y_col]]))
  if (nrow(df) == 0) return("")

  paste0(
    format(round(xf(df[[x_col]]), 1), trim = TRUE), ",",
    format(round(yf(df[[y_col]]), 1), trim = TRUE),
    collapse = " "
  )
}

pt_svg_ribbon_polygon <- function(df, lo_col, hi_col, xf, yf) {
  df <- df |>
    dplyr::filter(!is.na(.data[[lo_col]]), !is.na(.data[[hi_col]]), !is.na(water_day)) |>
    dplyr::arrange(water_day)

  if (nrow(df) < 2) return("")

  lo <- paste0(
    format(round(xf(df$water_day), 1), trim = TRUE), ",",
    format(round(yf(df[[lo_col]]), 1), trim = TRUE)
  )

  hi <- paste0(
    format(round(rev(xf(df$water_day)), 1), trim = TRUE), ",",
    format(round(rev(yf(df[[hi_col]])), 1), trim = TRUE)
  )

  paste(c(lo, hi), collapse = " ")
}

pt_month_ticks <- function() {
  tibble::tibble(
    water_day = c(1, 32, 62, 93, 124, 152, 183, 213, 244, 274, 305, 336),
    label = c("Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep")
  )
}

pt_context_fill <- function(x) {
  dplyr::case_when(
    x == "Much below normal" ~ "#8C510A",
    x == "Below normal"      ~ "#D8B365",
    x == "Near normal"       ~ "#7F7F7F",
    x == "Above normal"      ~ "#92C5DE",
    x == "Much above normal" ~ "#2166AC",
    TRUE                     ~ "#FFFFFF"
  )
}

pt_context_fill_opacity <- function(x) {
  dplyr::case_when(
    is.na(x) ~ 0,
    x == "No context" ~ 0,
    TRUE ~ 0.88
  )
}

pt_context_label <- function(sms_pct, p10, p30, p70, p90) {
  dplyr::case_when(
    is.na(sms_pct) | is.na(p10) | is.na(p30) | is.na(p70) | is.na(p90) ~ "No context",
    sms_pct <= p10 ~ "Much below normal",
    sms_pct <= p30 ~ "Below normal",
    sms_pct <= p70 ~ "Near normal",
    sms_pct <= p90 ~ "Above normal",
    sms_pct >  p90 ~ "Much above normal",
    TRUE ~ "No context"
  )
}


pt_scan_hover_html <- function(station_name, depth_label, sms_pct, context_label, age_label) {
  ## Keep hover text short but readable.  Four explicit rows are easier to scan
  ## than a single long line that wraps unpredictably in Leaflet tooltips.
  paste0(
    "<strong>", pt_esc(station_name), "</strong><br/>",
    pt_esc(depth_label), ": ", pt_esc(pt_fmt_num(sms_pct, 1)), "%<br/>",
    pt_esc(context_label), "<br/>",
    "Age: ", pt_esc(age_label)
  )
}

pt_fmt_mon_year <- function(x) {
  x <- as.Date(x)
  ifelse(is.na(x), "NA", format(x, "%b %Y"))
}

pt_fmt_wy_range <- function(wy_min, wy_max) {
  wy_min <- suppressWarnings(as.integer(wy_min))
  wy_max <- suppressWarnings(as.integer(wy_max))
  if (is.na(wy_min) || is.na(wy_max)) return("WY record unavailable")
  paste0("WY", wy_min, "–WY", wy_max)
}

pt_depth_record_meta <- function(site_code_arg, depth_in_arg, current_wy_arg = NA_integer_) {
  ## Depth-specific records can differ because sensors are installed, replaced,
  ## or retired independently.  This helper keeps the popup table and plot notes
  ## honest about the period of record / period of analysis for each depth.
  empty <- tibble::tibble(
    first_date = as.Date(NA),
    last_date = as.Date(NA),
    first_wy = NA_integer_,
    last_wy = NA_integer_,
    analysis_first_wy = NA_integer_,
    analysis_last_wy = NA_integer_,
    record_label = "Not available",
    analysis_label = "POA unavailable"
  )

  if (is.null(daily_history)) return(empty)

  x <- daily_history |>
    dplyr::filter(
      .data$site_code == site_code_arg,
      .data$depth_in == depth_in_arg,
      !is.na(.data$date),
      !is.na(.data$sms_pct)
    )

  if (nrow(x) == 0) return(empty)

  first_date <- min(x$date, na.rm = TRUE)
  last_date <- max(x$date, na.rm = TRUE)
  first_wy <- suppressWarnings(min(x$water_year, na.rm = TRUE))
  last_wy <- suppressWarnings(max(x$water_year, na.rm = TRUE))

  current_wy_arg <- suppressWarnings(as.integer(current_wy_arg))
  analysis_x <- x
  if (!is.na(current_wy_arg) && is.finite(current_wy_arg)) {
    analysis_x <- analysis_x |> dplyr::filter(.data$water_year < current_wy_arg)
  }

  if (nrow(analysis_x) > 0) {
    analysis_first_wy <- suppressWarnings(min(analysis_x$water_year, na.rm = TRUE))
    analysis_last_wy  <- suppressWarnings(max(analysis_x$water_year, na.rm = TRUE))
  } else {
    analysis_first_wy <- NA_integer_
    analysis_last_wy  <- NA_integer_
  }

  tibble::tibble(
    first_date = first_date,
    last_date = last_date,
    first_wy = first_wy,
    last_wy = last_wy,
    analysis_first_wy = analysis_first_wy,
    analysis_last_wy = analysis_last_wy,
    record_label = paste0(pt_fmt_mon_year(first_date), "–", pt_fmt_mon_year(last_date)),
    analysis_label = if (!is.na(analysis_first_wy) && !is.na(analysis_last_wy)) {
      paste0("WY", analysis_first_wy, "–WY", analysis_last_wy)
    } else {
      "POA unavailable"
    }
  )
}

pt_trace_current_wy <- function(tr) {
  if ("water_year" %in% names(tr)) {
    wy <- suppressWarnings(max(as.integer(tr$water_year), na.rm = TRUE))
    if (is.finite(wy)) return(as.integer(wy))
  }
  if ("obs_date" %in% names(tr) && any(!is.na(tr$obs_date))) {
    d <- max(as.Date(tr$obs_date), na.rm = TRUE)
    yr <- lubridate::year(d)
    mo <- lubridate::month(d)
    return(as.integer(ifelse(mo >= 10, yr + 1, yr)))
  }
  NA_integer_
}

pt_safe_id <- function(...) {
  x <- paste(..., sep = "-")
  x <- gsub("[^A-Za-z0-9_-]+", "-", x)
  x <- gsub("-+", "-", x)
  x
}

# ==== 5. Read sandbox inputs =================================================

pt_local_path_check(SCAN_LATEST_GEOJSON, "SCAN latest GeoJSON")
pt_local_path_check(SCAN_CURRENT_WY_TRACE_CSV, "SCAN current-WY trace CSV")
pt_local_path_check(SCAN_DEPTH_STYLE_CSV, "SCAN depth style CSV")
pt_local_path_check(SCAN_PERCENTILES_CSV, "SCAN water-day percentile CSV")

gj <- jsonlite::fromJSON(SCAN_LATEST_GEOJSON, simplifyVector = FALSE)

latest <- purrr::map_dfr(gj$features, function(feat) {
  props <- feat$properties
  coords <- feat$geometry$coordinates

  props <- lapply(props, function(x) {
    if (is.null(x)) return(NA)
    if (length(x) == 0) return(NA)
    if (length(x) == 1) return(x[[1]])
    paste(as.character(x), collapse = ", ")
  })

  tibble::as_tibble(props) |>
    dplyr::mutate(
      longitude = suppressWarnings(as.numeric(coords[[1]])),
      latitude  = suppressWarnings(as.numeric(coords[[2]]))
    )
}) |>
  dplyr::mutate(
    site_code = suppressWarnings(as.integer(site_code)),
    display_depth_in = suppressWarnings(as.numeric(display_depth_in)),
    display_sms_pct = suppressWarnings(as.numeric(display_sms_pct)),
    display_obs_age_days = suppressWarnings(as.integer(display_obs_age_days)),
    latitude = suppressWarnings(as.numeric(latitude)),
    longitude = suppressWarnings(as.numeric(longitude))
  )

if (!"display_depth_label" %in% names(latest)) {
  latest$display_depth_label <- ifelse(
    is.na(latest$display_depth_in),
    "NA",
    paste0(latest$display_depth_in, " in")
  )
}

if (!"display_status_label" %in% names(latest)) latest$display_status_label <- "NA"
if (!"display_context_label" %in% names(latest)) latest$display_context_label <- "No context"
if (!"display_timezone" %in% names(latest)) latest$display_timezone <- "America/Los_Angeles"
if (!"feed_build_time_local" %in% names(latest)) latest$feed_build_time_local <- NA_character_
if (!"depth_table_html" %in% names(latest)) latest$depth_table_html <- "Depth table not available"

trace_raw <- readr::read_csv(SCAN_CURRENT_WY_TRACE_CSV, show_col_types = FALSE)

trace <- trace_raw |>
  dplyr::mutate(
    site_code = suppressWarnings(as.integer(site_code)),
    depth_in = suppressWarnings(as.numeric(depth_in)),
    water_day = suppressWarnings(as.integer(water_day)),
    water_year = if ("water_year" %in% names(trace_raw)) suppressWarnings(as.integer(water_year)) else NA_integer_,
    obs_date = as.Date(obs_date),
    sms_pct = suppressWarnings(as.numeric(sms_pct))
  )

percentiles_raw <- readr::read_csv(SCAN_PERCENTILES_CSV, show_col_types = FALSE)

percentiles <- percentiles_raw |>
  dplyr::mutate(
    site_code = suppressWarnings(as.integer(site_code)),
    depth_in = suppressWarnings(as.numeric(depth_in)),
    water_day = suppressWarnings(as.integer(water_day)),
    p00 = if ("p00" %in% names(percentiles_raw)) suppressWarnings(as.numeric(p00)) else NA_real_,
    p10 = suppressWarnings(as.numeric(p10)),
    p30 = suppressWarnings(as.numeric(p30)),
    p50 = suppressWarnings(as.numeric(p50)),
    p70 = suppressWarnings(as.numeric(p70)),
    p90 = suppressWarnings(as.numeric(p90)),
    p100 = if ("p100" %in% names(percentiles_raw)) suppressWarnings(as.numeric(p100)) else NA_real_,
    n_years = suppressWarnings(as.integer(n_years))
  ) |>
  dplyr::mutate(
    p00 = dplyr::if_else(is.na(p00), p10, p00),
    p100 = dplyr::if_else(is.na(p100), p90, p100)
  )

depth_style <- readr::read_csv(SCAN_DEPTH_STYLE_CSV, show_col_types = FALSE) |>
  dplyr::mutate(
    depth_in = suppressWarnings(as.numeric(depth_in)),
    depth_order = suppressWarnings(as.integer(depth_order)),
    depth_color_hex = pt_chr(depth_color_hex),
    depth_label = pt_chr(depth_label)
  )

# ---- 5.1 Latest-by-depth table for sandbox map-depth selector ---------------
##
## The live-feed GeoJSON carries a JSON-encoded all-depth latest-value table
## (`depth_values_json`) for each station.  Use that as the FIRST choice for
## sandbox point recoloring because it is the same source that powers the popup
## latest-depth table.  This avoids a confusing mismatch where the popup has
## context but the map symbol says "No context" because the sandbox tried to
## recompute the latest context from separate trace/percentile tables.
##
## If an older feed is being tested and depth_values_json is not available, fall
## back to deriving latest depth values from the current-WY trace plus the
## historical percentile table.

latest_name_col <- if ("station_name" %in% names(latest)) {
  "station_name"
} else if ("station_name_display" %in% names(latest)) {
  "station_name_display"
} else {
  NA_character_
}

station_lookup <- latest |>
  dplyr::transmute(
    site_code = suppressWarnings(as.integer(.data$site_code)),
    station_name = if (!is.na(latest_name_col)) {
      as.character(.data[[latest_name_col]])
    } else {
      paste0("Site ", .data$site_code)
    }
  ) |>
  dplyr::distinct(.data$site_code, .keep_all = TRUE)

pt_depth_values_from_latest <- function(latest_df) {
  if (!"depth_values_json" %in% names(latest_df)) return(tibble::tibble())

  purrr::map_dfr(seq_len(nrow(latest_df)), function(i) {
    raw_json <- latest_df$depth_values_json[[i]]
    raw_json <- if (is.null(raw_json) || length(raw_json) == 0) NA_character_ else as.character(raw_json[[1]])
    if (is.na(raw_json) || !nzchar(raw_json)) return(tibble::tibble())

    vals <- tryCatch(
      jsonlite::fromJSON(raw_json, simplifyDataFrame = TRUE),
      error = function(e) NULL
    )
    if (is.null(vals) || length(vals) == 0) return(tibble::tibble())

    vals <- tibble::as_tibble(vals)
    if (nrow(vals) == 0) return(tibble::tibble())

    vals |>
      dplyr::mutate(
        site_code = suppressWarnings(as.integer(latest_df$site_code[[i]])),
        station_name = if (!is.na(latest_name_col)) {
          as.character(latest_df[[latest_name_col]][[i]])
        } else {
          paste0("Site ", latest_df$site_code[[i]])
        }
      )
  })
}

depth_latest_from_geojson <- pt_depth_values_from_latest(latest)

if (nrow(depth_latest_from_geojson) > 0) {

  depth_latest_for_map <- depth_latest_from_geojson |>
    dplyr::mutate(
      site_code = suppressWarnings(as.integer(.data$site_code)),
      depth_in = suppressWarnings(as.numeric(.data$depth_in)),
      sms_pct = suppressWarnings(as.numeric(.data$sms_pct)),
      obs_age_days = suppressWarnings(as.integer(.data$obs_age_days)),
      context_label = dplyr::coalesce(pt_chr(.data$context_label), "No context"),
      depth_label = dplyr::coalesce(pt_chr(.data$depth_label), paste0(.data$depth_in, " in")),
      marker_fill = pt_context_fill(.data$context_label),
      marker_fill_opacity = pt_context_fill_opacity(.data$context_label),
      obs_age_label = dplyr::case_when(
        is.na(.data$obs_age_days) ~ "not available",
        .data$obs_age_days <= 0 ~ "today",
        .data$obs_age_days == 1 ~ "1 day",
        TRUE ~ paste0(.data$obs_age_days, " days")
      ),
      hover_text = pt_scan_hover_html(
        .data$station_name,
        .data$depth_label,
        .data$sms_pct,
        .data$context_label,
        .data$obs_age_label
      )
    )

} else {

  depth_latest_for_map <- trace |>
    dplyr::group_by(.data$site_code, .data$depth_in) |>
    dplyr::filter(.data$obs_date == max(.data$obs_date, na.rm = TRUE)) |>
    dplyr::slice(1) |>
    dplyr::ungroup() |>
    dplyr::left_join(station_lookup, by = "site_code") |>
    dplyr::left_join(percentiles, by = c("site_code", "depth_in", "water_day")) |>
    dplyr::left_join(depth_style, by = "depth_in", suffix = c("", "_style"))

  if (!"depth_label" %in% names(depth_latest_for_map)) {
    depth_latest_for_map$depth_label <- NA_character_
  }
  if (!"depth_label_style" %in% names(depth_latest_for_map)) {
    depth_latest_for_map$depth_label_style <- NA_character_
  }

  depth_latest_for_map <- depth_latest_for_map |>
    dplyr::mutate(
      depth_label = dplyr::coalesce(.data$depth_label, .data$depth_label_style, paste0(.data$depth_in, " in")),
      context_label = pt_context_label(.data$sms_pct, .data$p10, .data$p30, .data$p70, .data$p90),
      marker_fill = pt_context_fill(.data$context_label),
      marker_fill_opacity = pt_context_fill_opacity(.data$context_label),
      obs_age_label = dplyr::case_when(
          is.na(.data$obs_date) ~ "not available",
          as.integer(max(.data$obs_date, na.rm = TRUE) - .data$obs_date) <= 0 ~ "today",
          TRUE ~ paste0(as.integer(max(.data$obs_date, na.rm = TRUE) - .data$obs_date), " days")
      ),
      hover_text = pt_scan_hover_html(
        .data$station_name,
        .data$depth_label,
        .data$sms_pct,
        .data$context_label,
        .data$obs_age_label
      )
    )
}

scan_depth_marker_lookup_df <- depth_latest_for_map |>
  dplyr::transmute(
    site_code = as.character(.data$site_code),
    depth_in = as.character(as.integer(.data$depth_in)),
    marker_fill,
    marker_fill_opacity,
    hover_text
  )

scan_depth_marker_lookup <- split(
  scan_depth_marker_lookup_df,
  scan_depth_marker_lookup_df$site_code
) |>
  purrr::map(function(df) {
    out <- split(df, df$depth_in)
    purrr::map(out, function(z) list(
      fill = z$marker_fill[1],
      fillOpacity = z$marker_fill_opacity[1],
      hover = z$hover_text[1]
    ))
  })

SCAN_DEPTHS_AVAILABLE <- sort(unique(depth_latest_for_map$depth_in[!is.na(depth_latest_for_map$depth_in)]))
SCAN_DEPTHS_AVAILABLE <- SCAN_DEPTHS_AVAILABLE[order(match(SCAN_DEPTHS_AVAILABLE, depth_style$depth_in))]

# ---- 5.2 Sandbox context QA -------------------------------------------------
##
## Before migrating this design into the full BRIM Ops Live layer, print the
## selected-depth context availability so gray/neutral points can be checked
## against the popup table.  Note that "Near normal" is intentionally neutral
## gray, while "No context" is a much lighter gray.

scan_context_qa <- depth_latest_for_map |>
  dplyr::mutate(
    depth_in = as.integer(.data$depth_in),
    context_label = dplyr::coalesce(pt_chr(.data$context_label), "No context")
  ) |>
  dplyr::count(.data$depth_in, .data$context_label, name = "n_stations") |>
  tidyr::pivot_wider(
    names_from = .data$context_label,
    values_from = .data$n_stations,
    values_fill = 0
  ) |>
  dplyr::arrange(.data$depth_in)

message("SCAN sandbox context counts by depth:")
print(scan_context_qa)

daily_history <- NULL
if (file.exists(SCAN_DAILY_HISTORY_RDS)) {
  message("Reading optional SCAN daily history for recent-record context trace: ", SCAN_DAILY_HISTORY_RDS)
  daily_history <- readRDS(SCAN_DAILY_HISTORY_RDS) |>
    tibble::as_tibble() |>
    dplyr::mutate(
      site_code = suppressWarnings(as.integer(site_code)),
      depth_in = suppressWarnings(as.numeric(depth_in)),
      water_day = suppressWarnings(as.integer(water_day)),
      water_year = suppressWarnings(as.integer(water_year)),
      date = as.Date(date),
      sms_pct = suppressWarnings(as.numeric(sms_pct))
    )
} else {
  message("Optional daily-history RDS not found; sandbox plots will omit the top recent-record context trace: ", SCAN_DAILY_HISTORY_RDS)
}

# ==== 6. Plot builders =======================================================

pt_build_recent_monthly_context <- function(site_code_arg, depth_in_arg) {
  ## Purpose:
  ##   Build a simple, intuitive recent-history context plot dataset.
  ##
  ## Design:
  ##   - Actual recent/available record is monthly median soil moisture.
  ##   - Historical monthly reference statistics are added only when enough
  ##     water years are available.  This avoids implying a climatological norm
  ##     from a station with only a few years of data.
  ##   - Current WY is excluded from the historical reference statistics.

  if (is.null(daily_history)) {
    return(list(actual = tibble::tibble(), ref = tibble::tibble(), meta = tibble::tibble()))
  }

  x <- daily_history |>
    dplyr::filter(
      .data$site_code == site_code_arg,
      .data$depth_in == depth_in_arg,
      !is.na(.data$date),
      !is.na(.data$sms_pct)
    ) |>
    dplyr::mutate(
      calendar_month = lubridate::month(.data$date),
      month_date = as.Date(format(.data$date, "%Y-%m-01"))
    )

  if (nrow(x) == 0) {
    return(list(actual = tibble::tibble(), ref = tibble::tibble(), meta = tibble::tibble()))
  }

  max_date <- max(x$date, na.rm = TRUE)
  first_date <- min(x$date, na.rm = TRUE)
  start_date <- as.Date(max_date %m-% lubridate::years(CONTEXT_YEARS_BACK))
  actual_start_date <- max(start_date, first_date, na.rm = TRUE)

  actual <- x |>
    dplyr::filter(.data$date >= actual_start_date) |>
    dplyr::group_by(.data$month_date, .data$calendar_month) |>
    dplyr::summarise(
      actual_sms_pct = stats::median(.data$sms_pct, na.rm = TRUE),
      n_days = dplyr::n(),
      .groups = "drop"
    ) |>
    dplyr::filter(.data$n_days >= 5, !is.na(.data$actual_sms_pct)) |>
    dplyr::arrange(.data$month_date)

  current_wy <- if ("water_year" %in% names(x)) max(x$water_year, na.rm = TRUE) else NA_integer_

  hist_ref <- x
  if (!is.na(current_wy) && is.finite(current_wy)) {
    hist_ref <- hist_ref |> dplyr::filter(.data$water_year < current_wy)
  }

  ref <- hist_ref |>
    dplyr::group_by(.data$calendar_month) |>
    dplyr::summarise(
      ref_p30 = as.numeric(stats::quantile(.data$sms_pct, 0.30, na.rm = TRUE, names = FALSE)),
      ref_p50 = stats::median(.data$sms_pct, na.rm = TRUE),
      ref_p70 = as.numeric(stats::quantile(.data$sms_pct, 0.70, na.rm = TRUE, names = FALSE)),
      ref_n_years = dplyr::n_distinct(.data$water_year[!is.na(.data$sms_pct)]),
      .groups = "drop"
    ) |>
    dplyr::filter(.data$ref_n_years >= CONTEXT_STAT_MIN_YEARS)

  ## Return the monthly reference as one row per calendar month.  Plot A later
  ## expands this into a complete repeating monthly reference sequence across
  ## the displayed years; do not join the reference to sparse actual months here.
  actual_years <- unique(lubridate::year(actual$month_date))
  ref_ok <- nrow(ref) >= 3

  meta <- tibble::tibble(
    first_date = first_date,
    last_date = max_date,
    actual_start_date = actual_start_date,
    actual_end_date = max_date,
    actual_n_months = nrow(actual),
    actual_n_years = length(actual_years),
    ref_ok = ref_ok,
    ref_min_years = if (nrow(ref) > 0) min(ref$ref_n_years, na.rm = TRUE) else NA_integer_,
    ref_max_years = if (nrow(ref) > 0) max(ref$ref_n_years, na.rm = TRUE) else NA_integer_,
    ref_first_date = if (nrow(hist_ref) > 0) min(hist_ref$date, na.rm = TRUE) else as.Date(NA),
    ref_last_date  = if (nrow(hist_ref) > 0) max(hist_ref$date, na.rm = TRUE) else as.Date(NA),
    ref_first_wy = if (nrow(hist_ref) > 0) suppressWarnings(min(hist_ref$water_year, na.rm = TRUE)) else NA_integer_,
    ref_last_wy  = if (nrow(hist_ref) > 0) suppressWarnings(max(hist_ref$water_year, na.rm = TRUE)) else NA_integer_
  )

  list(actual = actual, ref = ref, meta = meta)
}

pt_depth_options_for_site <- function(site_code_arg) {
  trace |>
    dplyr::filter(.data$site_code == site_code_arg, !is.na(.data$depth_in)) |>
    dplyr::distinct(.data$depth_in) |>
    dplyr::left_join(depth_style, by = "depth_in") |>
    dplyr::mutate(
      depth_order = dplyr::coalesce(.data$depth_order, 999L),
      depth_label = dplyr::coalesce(.data$depth_label, paste0(.data$depth_in, " in")),
      depth_color_hex = dplyr::coalesce(.data$depth_color_hex, "#333333")
    ) |>
    dplyr::arrange(.data$depth_order, .data$depth_in)
}


pt_make_depth_latest_table <- function(site_code_arg, current_wy_arg = NA_integer_) {
  ## Build the popup's latest-by-depth table locally so we can add a
  ## depth-specific period-of-record column.  The live feed remains the source
  ## of latest values and context labels; the local daily-history RDS supplies
  ## the POR dates used in this sandbox.

  rows <- depth_latest_for_map |>
    dplyr::filter(.data$site_code == site_code_arg) |>
    dplyr::left_join(depth_style, by = "depth_in", suffix = c("", "_style"))

  ## Make suffix-dependent columns explicit so this helper works whether the
  ## live feed already supplied depth labels/colors or they arrived only from
  ## scan_depth_style.csv.
  for (nm in c(
    "depth_order", "depth_order_style",
    "depth_label", "depth_label_style",
    "depth_color_hex", "depth_color_hex_style"
  )) {
    if (!nm %in% names(rows)) rows[[nm]] <- NA
  }

  rows <- rows |>
    dplyr::mutate(
      depth_order = dplyr::coalesce(.data$depth_order, .data$depth_order_style, 999L),
      depth_label = dplyr::coalesce(pt_chr(.data$depth_label), pt_chr(.data$depth_label_style), paste0(.data$depth_in, " in")),
      depth_color_hex = dplyr::coalesce(pt_chr(.data$depth_color_hex), pt_chr(.data$depth_color_hex_style), "#555555")
    ) |>
    dplyr::arrange(.data$depth_order, .data$depth_in)

  if (nrow(rows) == 0) {
    return("<div style='font-size:12px; color:#666;'>No latest depth values available.</div>")
  }

  row_html <- vapply(seq_len(nrow(rows)), function(i) {
    r <- rows[i, , drop = FALSE]

    por <- pt_depth_record_meta(
      site_code_arg = as.integer(site_code_arg),
      depth_in_arg = as.numeric(r$depth_in),
      current_wy_arg = current_wy_arg
    )

    latest_txt <- if (!is.na(r$sms_pct)) paste0(pt_fmt_num(r$sms_pct, 1), "%") else "NA"

    date_txt <- if ("obs_date" %in% names(r) && !is.na(r$obs_date)) {
      as.character(as.Date(r$obs_date))
    } else {
      "NA"
    }

    age_txt <- if ("obs_age_label" %in% names(r) && !is.na(r$obs_age_label)) {
      as.character(r$obs_age_label)
    } else {
      ""
    }

    context_txt <- if ("context_label" %in% names(r) && !is.na(r$context_label)) {
      as.character(r$context_label)
    } else {
      "No context"
    }

    if ("vs_median_pct_points" %in% names(r) && !is.na(r$vs_median_pct_points)) {
      diff_val <- suppressWarnings(as.numeric(r$vs_median_pct_points))
      if (!is.na(diff_val)) {
        context_txt <- paste0(context_txt, " (", ifelse(diff_val > 0, "+", ""), pt_fmt_num(diff_val, 1), " pts vs median)")
      }
    } else if ("display_vs_median_pct_points" %in% names(r) && !is.na(r$display_vs_median_pct_points)) {
      diff_val <- suppressWarnings(as.numeric(r$display_vs_median_pct_points))
      if (!is.na(diff_val)) {
        context_txt <- paste0(context_txt, " (", ifelse(diff_val > 0, "+", ""), pt_fmt_num(diff_val, 1), " pts vs median)")
      }
    }

    if ("n_years" %in% names(r) && !is.na(r$n_years)) {
      context_txt <- paste0(context_txt, "<br><span style='color:#666;'>", as.integer(r$n_years), " yrs</span>")
    }

    paste0(
      "<tr>",
      "<td style='white-space:nowrap; padding:1px 6px 1px 0;'>",
      "<span style='display:inline-block; width:8px; height:8px; border-radius:50%; background:", pt_esc(r$depth_color_hex), "; margin-right:4px;'></span>",
      pt_esc(r$depth_label), "</td>",
      "<td style='text-align:right; white-space:nowrap; padding:1px 8px 1px 0;'>", pt_esc(latest_txt), "</td>",
      "<td style='white-space:nowrap; padding:1px 8px 1px 0;'>", pt_esc(date_txt), "</td>",
      "<td style='white-space:nowrap; padding:1px 8px 1px 0;'>", ifelse(nzchar(age_txt), pt_esc(age_txt), "NA"), "</td>",
      "<td style='padding:1px 8px 1px 0;'>", context_txt, "</td>",
      "<td style='white-space:nowrap; padding:1px 0;'>", pt_esc(por$record_label[1]), "</td>",
      "</tr>"
    )
  }, character(1))

  paste0(
    "<table style='font-size:12px; border-collapse:collapse;'>",
    "<thead><tr>",
    "<th style='text-align:left; padding-right:6px;'>Depth</th>",
    "<th style='text-align:right; padding-right:8px;'>Latest</th>",
    "<th style='text-align:left; padding-right:8px;'>Date</th>",
    "<th style='text-align:left; padding-right:8px;'>Age</th>",
    "<th style='text-align:left; padding-right:8px;'>Historical context</th>",
    "<th style='text-align:left;'>Record</th>",
    "</tr></thead><tbody>",
    paste(row_html, collapse = ""),
    "</tbody></table>"
  )
}

pt_make_scan_svg <- function(site_code_arg, station_name, depth_in_arg = PLOT_DEPTH_IN) {

  p <- percentiles |>
    dplyr::filter(.data$site_code == site_code_arg, .data$depth_in == depth_in_arg) |>
    dplyr::arrange(.data$water_day)

  tr <- trace |>
    dplyr::filter(.data$site_code == site_code_arg, .data$depth_in == depth_in_arg) |>
    dplyr::arrange(.data$water_day)

  current_wy <- pt_trace_current_wy(tr)
  daily_record_meta <- pt_depth_record_meta(site_code_arg, depth_in_arg, current_wy)

  ## Use daily ribbons only where enough historical years support the
  ## station/depth/day envelope.  Very new stations still show their current-WY
  ## trace but do not pretend to have a stable climatological envelope.
  p_for_ribbons <- p
  if ("n_years" %in% names(p_for_ribbons)) {
    p_for_ribbons <- p_for_ribbons |>
      dplyr::filter(!is.na(.data$n_years), .data$n_years >= DAILY_RIBBON_MIN_YEARS)
  } else {
    p_for_ribbons <- p_for_ribbons[0, , drop = FALSE]
  }
  daily_context_ok <- nrow(p_for_ribbons) >= 30
  daily_years_min <- if (nrow(p) > 0 && "n_years" %in% names(p)) {
    suppressWarnings(min(p$n_years, na.rm = TRUE))
  } else {
    NA_integer_
  }
  daily_years_max <- if (nrow(p) > 0 && "n_years" %in% names(p)) {
    suppressWarnings(max(p$n_years, na.rm = TRUE))
  } else {
    NA_integer_
  }

  style_row <- depth_style |>
    dplyr::filter(.data$depth_in == depth_in_arg) |>
    dplyr::slice(1)

  depth_label <- if (nrow(style_row) > 0 && !is.na(style_row$depth_label[1])) {
    style_row$depth_label[1]
  } else {
    paste0(depth_in_arg, " in")
  }

  depth_color <- if (nrow(style_row) > 0 && !is.na(style_row$depth_color_hex[1])) {
    style_row$depth_color_hex[1]
  } else {
    "#333333"
  }

  if (nrow(tr) == 0) {
    return(paste0(
      "<div style='font-size:12px; color:#666; border-left:4px solid ", depth_color, "; padding-left:6px;'>",
      "No current-water-year plot data available for ", pt_esc(depth_label), " at this station.</div>"
    ))
  }

  recent_ctx <- pt_build_recent_monthly_context(site_code_arg, depth_in_arg)
  recent_actual <- recent_ctx$actual
  recent_ref <- recent_ctx$ref
  recent_meta <- recent_ctx$meta

  w <- SVG_WIDTH
  h <- SVG_HEIGHT
  ml <- 46
  mr <- 14
  mt <- 22
  context_h <- if (nrow(recent_actual) >= 3) 86 else 0
  gap <- if (context_h > 0) 14 else 0
  plot_top <- mt + context_h + gap
  mb <- 34
  plot_h <- h - plot_top - mb
  plot_w <- w - ml - mr

  vals <- if (daily_context_ok) {
    c(p_for_ribbons$p00, p_for_ribbons$p10, p_for_ribbons$p30, p_for_ribbons$p50, p_for_ribbons$p70, p_for_ribbons$p90, p_for_ribbons$p100, tr$sms_pct)
  } else {
    c(tr$sms_pct)
  }
  vals <- vals[is.finite(vals)]
  y_min <- max(0, floor(min(vals, na.rm = TRUE) / 5) * 5)
  y_max <- ceiling(max(vals, na.rm = TRUE) / 5) * 5
  if (!is.finite(y_min) || !is.finite(y_max) || y_min == y_max) {
    y_min <- 0
    y_max <- 50
  }

  xf <- function(x) ml + ((x - 1) / 365) * plot_w
  yf <- function(y) plot_top + plot_h - ((y - y_min) / (y_max - y_min)) * plot_h

  month_ticks <- pt_month_ticks()

  ribbon_defs <- tibble::tribble(
    ~lo,  ~hi,    ~fill,      ~label,
    "p00", "p10", "#EAD6B8", "min-p10",
    "p10", "p30", "#F4EAD8", "p10-p30",
    "p30", "p70", "#ECECEC", "p30-p70",
    "p70", "p90", "#DDEEF7", "p70-p90",
    "p90", "p100", "#BFD7EA", "p90-max"
  )

  ribbons <- if (daily_context_ok) {
    purrr::pmap_chr(ribbon_defs, function(lo, hi, fill, label) {
      pts <- pt_svg_ribbon_polygon(p_for_ribbons, lo, hi, xf, yf)
      if (!nzchar(pts)) return("")
      paste0("<polygon points='", pts, "' fill='", fill, "' opacity='0.95'/>")
    }) |> paste(collapse = "")
  } else {
    ""
  }

  median_pts <- if (daily_context_ok) pt_svg_line(p_for_ribbons, "water_day", "p50", xf, yf) else ""
  median_line <- if (nzchar(median_pts)) {
    paste0("<polyline points='", median_pts, "' fill='none' stroke='#666666' stroke-width='1.2' stroke-dasharray='3 3'/>")
  } else ""

  trace_pts <- pt_svg_line(tr, "water_day", "sms_pct", xf, yf)
  trace_line <- if (nzchar(trace_pts)) {
    paste0("<polyline points='", trace_pts, "' fill='none' stroke='#111111' stroke-width='2.2'/>")
  } else ""

  latest_pt <- tr |> dplyr::filter(.data$obs_date == max(.data$obs_date, na.rm = TRUE)) |> dplyr::slice(1)
  latest_dot <- if (nrow(latest_pt) == 1) {
    ## RF055c: match the latest daily marker to the selected depth color,
    ## while leaving the current-WY trace line black for contrast.
    paste0(
      "<circle cx='", round(xf(latest_pt$water_day), 1), "' cy='", round(yf(latest_pt$sms_pct), 1),
      "' r='3.8' fill='", depth_color, "' stroke='white' stroke-width='1'/>")
  } else ""

  y_ticks <- pretty(c(y_min, y_max), n = 4)
  y_ticks <- y_ticks[y_ticks >= y_min & y_ticks <= y_max]

  ## RF048: keep y-axis tick labels only.  Full-width grid lines were
  ## visually distracting in the small popup plot and competed with the
  ## translucent percentile ribbons.
  grid <- paste0(
    purrr::map_chr(y_ticks, function(yy) {
      paste0(
        "<text x='", ml - 6, "' y='", round(yf(yy) + 4, 1), "' text-anchor='end' font-size='10' fill='#555'>", yy, "</text>"
      )
    }),
    collapse = ""
  )

  x_axis <- paste0(
    purrr::pmap_chr(month_ticks, function(water_day, label) {
      paste0(
        "<line x1='", round(xf(water_day), 1), "' x2='", round(xf(water_day), 1), "' y1='", plot_top + plot_h,
        "' y2='", plot_top + plot_h + 4, "' stroke='#555'/>",
        "<text x='", round(xf(water_day), 1), "' y='", plot_top + plot_h + 17, "' text-anchor='middle' font-size='10' fill='#555'>", label, "</text>"
      )
    }),
    collapse = ""
  )

  context_svg <- ""
  if (nrow(recent_actual) >= 3) {
    cx0 <- ml
    cy0 <- mt + 16
    ch <- context_h - 34
    cw <- plot_w

    c_dates <- as.numeric(recent_actual$month_date)
    c_min_date <- min(c_dates, na.rm = TRUE)
    c_max_date <- max(c_dates, na.rm = TRUE)

    recent_ref_by_month <- recent_ref |>
      dplyr::mutate(calendar_month = suppressWarnings(as.integer(.data$calendar_month))) |>
      dplyr::filter(
        !is.na(.data$calendar_month),
        !is.na(.data$ref_p30),
        !is.na(.data$ref_p50),
        !is.na(.data$ref_p70)
      ) |>
      dplyr::distinct(.data$calendar_month, .keep_all = TRUE) |>
      dplyr::select("calendar_month", "ref_p30", "ref_p50", "ref_p70")

    ref_month_seq <- seq.Date(
      from = as.Date(format(min(recent_actual$month_date, na.rm = TRUE), "%Y-%m-01")),
      to = as.Date(format(max(recent_actual$month_date, na.rm = TRUE), "%Y-%m-01")),
      by = "month"
    )

    recent_ref_plot <- tibble::tibble(
      month_date = ref_month_seq,
      calendar_month = lubridate::month(ref_month_seq)
    ) |>
      dplyr::left_join(recent_ref_by_month, by = "calendar_month") |>
      dplyr::filter(!is.na(.data$ref_p50)) |>
      dplyr::arrange(.data$month_date)

    ref_vals <- if (nrow(recent_ref_plot) > 0) c(recent_ref_plot$ref_p30, recent_ref_plot$ref_p50, recent_ref_plot$ref_p70) else numeric(0)
    c_vals <- c(recent_actual$actual_sms_pct, ref_vals)
    c_vals <- c_vals[is.finite(c_vals)]

    c_y_min <- max(0, floor(min(c_vals, na.rm = TRUE) / 5) * 5)
    c_y_max <- ceiling(max(c_vals, na.rm = TRUE) / 5) * 5
    if (!is.finite(c_y_min) || !is.finite(c_y_max) || c_y_min == c_y_max) {
      c_y_min <- y_min
      c_y_max <- y_max
    }

    cxf <- function(d) cx0 + ((as.numeric(d) - c_min_date) / max(1, c_max_date - c_min_date)) * cw
    cyf <- function(y) cy0 + ch - ((y - c_y_min) / (c_y_max - c_y_min)) * ch

    ## Historical monthly reference band and median, repeated across the recent
    ## monthly time axis.  This is shown only where the station/depth has enough
    ## years to support a stable reference trace.
    ref_band <- ""
    ref_line <- ""
    ref_note <- paste0("Monthly stats shown where ≥", CONTEXT_STAT_MIN_YEARS, " years support the reference")

    if (nrow(recent_ref_plot) >= 3) {
      ref_band_pts <- paste(
        c(
          paste0(
            format(round(cxf(recent_ref_plot$month_date), 1), trim = TRUE), ",",
            format(round(cyf(recent_ref_plot$ref_p30), 1), trim = TRUE)
          ),
          paste0(
            format(round(rev(cxf(recent_ref_plot$month_date)), 1), trim = TRUE), ",",
            format(round(rev(cyf(recent_ref_plot$ref_p70)), 1), trim = TRUE)
          )
        ),
        collapse = " "
      )
      ref_band <- paste0("<polygon points='", ref_band_pts, "' fill='#D9D9D9' opacity='0.42'/>")

      ref_pts <- pt_svg_line(recent_ref_plot, "month_date", "ref_p50", cxf, cyf)
      if (nzchar(ref_pts)) {
        ref_line <- paste0("<polyline points='", ref_pts, "' fill='none' stroke='#666666' stroke-width='1.1' stroke-dasharray='4 3'/>")
      }
    } else {
      ref_note <- paste0("Actual monthly values shown; monthly reference hidden because <", CONTEXT_STAT_MIN_YEARS, " years are available")
    }

    actual_line_pts <- pt_svg_line(recent_actual, "month_date", "actual_sms_pct", cxf, cyf)
    actual_line <- if (nzchar(actual_line_pts)) {
      paste0("<polyline points='", actual_line_pts, "' fill='none' stroke='#111111' stroke-width='1.7'/>")
    } else ""

    ## RF055c: add small monthly point markers so gaps in the recent context
    ## trace are visually obvious instead of looking like flat/constant data.
    actual_points <- if (nrow(recent_actual) > 0) {
      paste0(
        purrr::pmap_chr(
          recent_actual,
          function(month_date, calendar_month, actual_sms_pct, n_days, ...) {
            if (is.na(month_date) || is.na(actual_sms_pct)) return("")
            paste0(
              "<circle cx='", round(cxf(month_date), 1),
              "' cy='", round(cyf(actual_sms_pct), 1),
              "' r='1.8' fill='#111111' opacity='0.72'/>"
            )
          }
        ),
        collapse = ""
      )
    } else ""

    c_latest <- recent_actual |>
      dplyr::filter(.data$month_date == max(.data$month_date, na.rm = TRUE)) |>
      dplyr::slice(1)

    c_latest_dot <- if (nrow(c_latest) == 1) {
      paste0(
        "<circle cx='", round(cxf(c_latest$month_date), 1), "' cy='", round(cyf(c_latest$actual_sms_pct), 1),
        "' r='3' fill='", depth_color, "' stroke='white' stroke-width='1'/>")
    } else ""

    years <- sort(unique(lubridate::year(recent_actual$month_date)))
    lab_years <- years[years %% 2 == 0]
    if (length(lab_years) == 0) lab_years <- years[seq(1, length(years), length.out = min(4, length(years)))] |> unique()

    year_labels <- purrr::map_chr(lab_years, function(yr) {
      xd <- as.Date(paste0(yr, "-01-01"))
      if (xd < min(recent_actual$month_date) || xd > max(recent_actual$month_date)) return("")
      paste0("<text x='", round(cxf(xd), 1), "' y='", cy0 + ch + 11, "' text-anchor='middle' font-size='9' fill='#666'>", yr, "</text>")
    }) |> paste(collapse = "")

    context_label <- if (nrow(recent_meta) == 1 && !is.na(recent_meta$actual_start_date[1])) {
      paste0(
        "A. Monthly context — showing ",
        format(recent_meta$actual_start_date[1], "%Y"), "–", format(recent_meta$actual_end_date[1], "%Y")
      )
    } else {
      "A. Monthly context"
    }

    monthly_poa_label <- if (nrow(recent_meta) == 1 && !is.na(recent_meta$ref_first_date[1])) {
      paste0(pt_fmt_mon_year(recent_meta$ref_first_date[1]), "–", pt_fmt_mon_year(recent_meta$ref_last_date[1]))
    } else {
      "POA unavailable"
    }

    context_svg <- paste0(
      "<text x='", ml, "' y='", mt + 7, "' font-size='10' fill='#333'>", pt_esc(context_label), "</text>",
      "",
      "<rect x='", cx0, "' y='", cy0, "' width='", cw, "' height='", ch, "' fill='#F7F7F7' stroke='#D8D8D8' stroke-width='1'/>",
      ref_band,
      ref_line,
      actual_line,
      actual_points,
      c_latest_dot,
      "<text x='", ml - 6, "' y='", round(cyf(c_y_min) + 3, 1), "' text-anchor='end' font-size='8' fill='#666'>", c_y_min, "</text>",
      "<text x='", ml - 6, "' y='", round(cyf(c_y_max) + 3, 1), "' text-anchor='end' font-size='8' fill='#666'>", c_y_max, "</text>",
      year_labels
    )
  }

  current_wy_label <- if (!is.na(current_wy)) paste0("WY ", current_wy) else "current WY"
  daily_poa_label <- daily_record_meta$analysis_label[1]

  lower_title <- if (daily_context_ok) {
    paste0("B. Daily envelope — ", current_wy_label, " vs historical daily percentiles")
  } else {
    paste0("B. Daily trace — ", current_wy_label, " (historical envelope limited)")
  }

  monthly_poa_note <- if (exists("monthly_poa_label")) monthly_poa_label else "POA unavailable"

  daily_note <- if (daily_context_ok) {
    paste0(
      "ribbons = prior-year daily percentiles (min–10th, 10th–30th, 30th–70th, 70th–90th, 90th–max) where ≥",
      DAILY_RIBBON_MIN_YEARS,
      " years of data are available; max by date = ",
      if (!is.na(daily_years_max)) paste0(daily_years_max, " yrs") else "NA",
      "; POA ", daily_poa_label,
      ". Dashed=median; black=current WY."
    )
  } else {
    paste0("current WY shown only; daily percentile envelope hidden because <", DAILY_RIBBON_MIN_YEARS, " years of data are available for this station/depth; POA ", daily_poa_label, ".")
  }

  paste0(
    "<div class='scan-plot-shell'>",
    "<svg width='", w, "' height='", h, "' viewBox='0 0 ", w, " ", h, "' xmlns='http://www.w3.org/2000/svg' style='max-width:100%; height:auto; background:#FAFAFA; border:1px solid #DDD;'>",
    "<rect x='0' y='0' width='", w, "' height='", h, "' fill='#FAFAFA'/>",
    "<text x='10' y='14' font-size='12' font-weight='bold' fill='#222'>", pt_esc(station_name), " — ", pt_esc(depth_label), " soil moisture</text>",
    "",
    context_svg,
    "<text x='", ml, "' y='", plot_top - 6, "' font-size='10' fill='#333'>", pt_esc(lower_title), "</text>",
    "<rect x='", ml, "' y='", plot_top, "' width='", plot_w, "' height='", plot_h, "' fill='#F7F7F7' stroke='#D0D0D0' stroke-width='1'/>",
    ribbons,
    grid,
    median_line,
    trace_line,
    latest_dot,
    "<line x1='", ml, "' x2='", ml + plot_w, "' y1='", plot_top + plot_h, "' y2='", plot_top + plot_h, "' stroke='#555'/>",
    x_axis,
    "<text transform='translate(12,", plot_top + plot_h / 2, ") rotate(-90)' text-anchor='middle' font-size='10' fill='#555'>Volumetric water content (%)</text>",
    "",
    "</svg>",
    "<div class='scan-plot-note'><b>A. Monthly context:</b> black = actual monthly median; gray band/line = repeated historical monthly 30th–70th percentile and median when &ge;", CONTEXT_STAT_MIN_YEARS, " years of data are available; stats POA ", pt_esc(monthly_poa_note), "; plot shows recent/available record for space.</div>",
    "<div class='scan-plot-note'><b>B. Daily envelope:</b> ", pt_esc(daily_note), "</div>",
    "</div>"
  )
}

pt_make_depth_tabs <- function(site_code_arg, station_name, active_depth_arg = PLOT_DEPTH_IN) {
  depths <- pt_depth_options_for_site(site_code_arg)

  if (nrow(depths) == 0) {
    return("<div style='font-size:12px; color:#666;'>No depth plots available for this station.</div>")
  }

  active_depth <- if (active_depth_arg %in% depths$depth_in) active_depth_arg else depths$depth_in[1]
  tab_group_id <- pt_safe_id("scan-tabs", site_code_arg)

  buttons <- vapply(seq_len(nrow(depths)), function(i) {
    d <- depths[i, , drop = FALSE]
    panel_id <- pt_safe_id(tab_group_id, d$depth_in)
    active_class <- if (d$depth_in == active_depth) " active" else ""
    paste0(
      "<button type='button' class='scan-depth-tab", active_class, "' data-depth='", as.integer(d$depth_in), "' data-target='", panel_id, "'>",
      "<span class='scan-depth-dot' style='background:", pt_esc(d$depth_color_hex), "'></span>",
      pt_esc(d$depth_label),
      "</button>"
    )
  }, character(1)) |> paste(collapse = "")

  panels <- vapply(seq_len(nrow(depths)), function(i) {
    d <- depths[i, , drop = FALSE]
    panel_id <- pt_safe_id(tab_group_id, d$depth_in)
    active_class <- if (d$depth_in == active_depth) " active" else ""
    paste0(
      "<div id='", panel_id, "' class='scan-depth-panel", active_class, "' data-depth='", as.integer(d$depth_in), "'>",
      pt_make_scan_svg(site_code_arg, station_name, d$depth_in),
      "</div>"
    )
  }, character(1)) |> paste(collapse = "")

  paste0(
    "<div class='scan-depth-tabs' id='", tab_group_id, "'>",
    "<div class='scan-depth-tab-row'>", buttons, "</div>",
    panels,
    "</div>"
  )
}

pt_make_sandbox_popup <- function(row, active_depth_arg = PLOT_DEPTH_IN) {
  site_code_arg <- as.integer(row$site_code)
  station_name <- as.character(row$station_name)

  latest_line <- if (!is.na(row$display_sms_pct)) {
    paste0(pt_fmt_num(row$display_sms_pct, 1), "% at ", row$display_depth_label)
  } else {
    "Not available"
  }

  tabs_html <- pt_make_depth_tabs(site_code_arg, station_name, active_depth_arg)

  paste0(
    "<div class='scan-popup-wrap'>",
    "<div style='font-size:14px; font-weight:bold; margin-bottom:2px;'>", pt_esc(station_name), "</div>",
    "<div style='font-size:12px; color:#555; margin-bottom:4px;'>Station ", pt_esc(site_code_arg),
    " · ", pt_esc(row$county), ", ", pt_esc(row$state),
    " · ", ifelse(is.na(row$elevation_ft), "elev. NA", paste0("elev. ", formatC(as.numeric(row$elevation_ft), format = "f", digits = 0, big.mark = ","), " ft")),
    "</div>",
    "<div style='font-size:12px; margin-bottom:5px;'>Depth tabs below show the latest value, recent monthly context, and current-water-year daily envelope for each available depth.</div>",
    "<div style='margin-bottom:6px; font-size:12px;'><b>Latest by depth:</b><br>", pt_make_depth_latest_table(site_code_arg, pt_trace_current_wy(trace)), "</div>",
    tabs_html,
    "<div style='font-size:11px; color:#666; margin-top:4px;'>Depth tabs show available soil sensors. Where duplicate same-depth sensors exist, sandbox plots use the primary NRCS sensor rather than averaging duplicates. UTC retained internally; display fields use ",
    pt_esc(row$display_timezone), ". Feed built: ", pt_esc(row$feed_build_time_local), ".</div>",
    if (!is.null(row$site_page_url) && !is.na(row$site_page_url) && nzchar(as.character(row$site_page_url))) {
      paste0("<div style='font-size:12px; margin-top:5px;'><a href='", pt_esc(row$site_page_url), "' target='_blank' rel='noopener noreferrer'>Open official NRCS station page</a></div>")
    } else {
      ""
    },
    "</div>"
  )
}

# ==== 7. Build popup HTML and sandbox map ===================================

## Build popup HTML outside dplyr::mutate().
latest$sandbox_popup_html <- vapply(
  seq_len(nrow(latest)),
  function(i) pt_make_sandbox_popup(latest[i, , drop = FALSE], PLOT_DEPTH_IN),
  character(1)
)

latest <- latest |>
  dplyr::mutate(
    marker_fill = pt_context_fill(.data$display_context_label),
    marker_fill_opacity = pt_context_fill_opacity(.data$display_context_label),
    marker_radius = dplyr::case_when(
      is.na(.data$display_sms_pct) ~ 5,
      TRUE ~ 7
    ),
    hover_text = pt_scan_hover_html(
      .data$station_name,
      .data$display_depth_label,
      .data$display_sms_pct,
      .data$display_context_label,
      .data$display_status_label
    )
  )

latest$hover_label_html <- lapply(latest$hover_text, htmltools::HTML)

map_center_lng <- stats::median(latest$longitude, na.rm = TRUE)
map_center_lat <- stats::median(latest$latitude, na.rm = TRUE)

m <- leaflet::leaflet(latest, options = leaflet::leafletOptions(preferCanvas = TRUE)) |>
  leaflet::addProviderTiles(leaflet::providers$CartoDB.Positron) |>
  leaflet::setView(lng = map_center_lng, lat = map_center_lat, zoom = 6) |>
  leaflet::addCircleMarkers(
    lng = ~longitude,
    lat = ~latitude,
    radius = ~marker_radius,
    stroke = TRUE,
    color = "#222222",
    weight = 1,
    fillColor = ~marker_fill,
    fillOpacity = ~marker_fill_opacity,
    label = latest$hover_label_html,
    labelOptions = leaflet::labelOptions(
      direction = "auto",
      opacity = 0.95,
      className = "scan-sandbox-tooltip"
    ),
    popup = ~sandbox_popup_html,
    popupOptions = leaflet::popupOptions(maxWidth = 660, minWidth = 630, keepInView = TRUE),
    layerId = ~as.character(site_code),
    group = "SCAN popup sandbox"
  ) |>
  leaflet::addControl(
    html = paste0(
      "<div style='background:white; padding:8px; border:1px solid #AAA; border-radius:4px; max-width:340px;'>",
      "<b>BRIM SCAN popup sandbox</b><br>",
      "<span style='font-size:12px;'>Fast dev map for testing SCAN hover/popup/SVG design. ",
      "This is not the full BRIM map. Use the SCAN depth buttons to recolor symbols.</span>",
      "</div>"
    ),
    position = "topright"
  )

# ---- 7.1 Browser-side CSS, popup-tab behavior, and compact SCAN controls ----

depth_control_html <- paste0(
  "<div class='scan-map-depth-control-box'>",
  "<div class='scan-control-title'>SCAN depth</div>",
  "<div class='scan-depth-control'>",
  paste0(
    purrr::map_chr(SCAN_DEPTHS_AVAILABLE, function(d) {
      active <- if (as.integer(d) == PLOT_DEPTH_IN) " active" else ""
      paste0(
        "<button type='button' class='scan-map-depth-btn", active, "' data-depth='", as.integer(d), "'>", as.integer(d), "</button>"
      )
    }),
    collapse = ""
  ),
  "</div>",
  "</div>"
)

legend_html <- paste0(
  "<div class='scan-map-legend-box'>",
  "<div class='scan-control-title'>SCAN context</div>",
  "<div class='scan-map-legend-title'>Latest <span class='scan-selected-depth-label'>", PLOT_DEPTH_IN, "</span>-in context</div>",
  "<div class='scan-legend-grid'>",
  "<div class='scan-legend-row'><span style='background:#8C510A'></span>Much below</div>",
  "<div class='scan-legend-row'><span style='background:#D8B365'></span>Below</div>",
  "<div class='scan-legend-row'><span style='background:#7F7F7F'></span>Near normal</div>",
  "<div class='scan-legend-row'><span style='background:#92C5DE'></span>Above</div>",
  "<div class='scan-legend-row'><span style='background:#2166AC'></span>Much above</div>",
  "<div class='scan-legend-row'><span style='background:transparent; border:2px solid #777; box-sizing:border-box;'></span>No context</div>",
  "</div>",
  "</div>"
)

depth_control_json <- jsonlite::toJSON(depth_control_html, auto_unbox = TRUE)
legend_json <- jsonlite::toJSON(legend_html, auto_unbox = TRUE)
marker_lookup_json <- jsonlite::toJSON(scan_depth_marker_lookup, auto_unbox = TRUE, null = "null")
initial_depth_json <- jsonlite::toJSON(as.character(PLOT_DEPTH_IN), auto_unbox = TRUE)

m <- htmlwidgets::onRender(
  m,
  paste0(
    "function(el, x) {\n",
    "  var map = this;\n",
    "  var scanMarkerLookup = ", marker_lookup_json, ";\n",
    "  var scanSelectedDepth = ", initial_depth_json, ";\n",
    "  if (!document.getElementById('scan-sandbox-style')) {\n",
    "    var style = document.createElement('style');\n",
    "    style.id = 'scan-sandbox-style';\n",
    "    style.innerHTML = `\n",
    "      .scan-sandbox-tooltip { white-space:nowrap; line-height:1.25; max-width:none; }\n",
    "      .scan-popup-wrap { width: 630px; max-width: 630px; font-family: Arial, sans-serif; }\n",
    "      .scan-depth-tab-row { display:flex; flex-wrap:wrap; gap:4px; margin:5px 0 6px 0; }\n",
    "      .scan-depth-tab { border:1px solid #B8B8B8; background:#F6F6F6; border-radius:4px; padding:3px 7px; font-size:12px; cursor:pointer; }\n",
    "      .scan-depth-tab.active { background:#FFFFFF; border-color:#333333; font-weight:bold; box-shadow:0 1px 3px rgba(0,0,0,0.18); }\n",
    "      .scan-depth-dot { display:inline-block; width:9px; height:9px; border-radius:50%; margin-right:4px; vertical-align:-1px; }\n",
    "      .scan-depth-panel { display:none; }\n",
    "      .scan-depth-panel.active { display:block; }\n",
    "      .scan-plot-shell { margin-top:4px; }\n",
    "      .scan-plot-note { font-size:10.5px; color:#555; line-height:1.25; margin:2px 2px 0 2px; }\n",
    "      .scan-depth-top-left-control, .scan-legend-top-left-control { background:rgba(255,255,255,0.94); border:1px solid #AAA; border-radius:5px; padding:6px 8px; box-shadow:0 1px 5px rgba(0,0,0,0.25); font:12px/1.2 Arial, sans-serif; }\n      .scan-depth-top-left-control { min-width:118px; }\n      .scan-legend-top-left-control { min-width:190px; }\n",
    "      .scan-control-title { font-weight:bold; margin-bottom:4px; }\n",
    "      .scan-depth-control { display:flex; align-items:center; gap:3px; white-space:nowrap; }\n",
    "",
    "      .scan-map-depth-btn { border:1px solid #999; background:#F7F7F7; border-radius:3px; padding:1px 4px; font-size:11px; line-height:1.2; cursor:pointer; }\n",
    "      .scan-map-depth-btn.active { background:#FFFFFF; border-color:#111; font-weight:bold; box-shadow:0 1px 2px rgba(0,0,0,0.2); }\n",
    "      .scan-map-legend-title { font-weight:bold; margin-bottom:3px; font-size:11px; }\n",
    "      .scan-legend-grid { display:grid; grid-template-columns:1fr 1fr; column-gap:8px; row-gap:2px; }\n",
    "      .scan-legend-top-left-control .scan-legend-row { white-space:nowrap; font-size:11px; }\n",
    "      .scan-legend-top-left-control .scan-legend-row span { display:inline-block; width:10px; height:10px; border:1px solid rgba(0,0,0,0.25); margin-right:3px; vertical-align:-1px; }\n",
    "    `;\n",
    "    document.head.appendChild(style);\n",
    "  }\n",
    "\n",
    "  if (!el._scanSandboxTabsBound) {\n",
    "    el.addEventListener('click', function(e) {\n",
    "      var btn = e.target.closest ? e.target.closest('.scan-depth-tab') : null;\n",
    "      if (!btn) return;\n",
    "      var wrap = btn.closest('.scan-depth-tabs');\n",
    "      if (!wrap) return;\n",
    "      var target = btn.getAttribute('data-target');\n",
    "      Array.prototype.forEach.call(wrap.querySelectorAll('.scan-depth-tab'), function(b) { b.classList.remove('active'); });\n",
    "      Array.prototype.forEach.call(wrap.querySelectorAll('.scan-depth-panel'), function(p) { p.classList.remove('active'); });\n",
    "      btn.classList.add('active');\n",
    "      var panel = wrap.querySelector('#' + target);\n",
    "      if (panel) panel.classList.add('active');\n",
    "    });\n",
    "    el._scanSandboxTabsBound = true;\n",
    "  }\n",
    "\n",
    "  function scanSetPopupDepth(root, depth) {\n",
    "    if (!root) return;\n",
    "    var btn = root.querySelector('.scan-depth-tab[data-depth=\"' + depth + '\"]');\n",
    "    if (!btn) return;\n",
    "    var wrap = btn.closest('.scan-depth-tabs');\n",
    "    if (!wrap) return;\n",
    "    var target = btn.getAttribute('data-target');\n",
    "    Array.prototype.forEach.call(wrap.querySelectorAll('.scan-depth-tab'), function(b) { b.classList.remove('active'); });\n",
    "    Array.prototype.forEach.call(wrap.querySelectorAll('.scan-depth-panel'), function(p) { p.classList.remove('active'); });\n",
    "    btn.classList.add('active');\n",
    "    var panel = wrap.querySelector('#' + target);\n",
    "    if (panel) panel.classList.add('active');\n",
    "  }\n",
    "\n",
    "  function scanApplyDepth(depth) {\n",
    "    scanSelectedDepth = String(depth);\n",
    "    Array.prototype.forEach.call(el.querySelectorAll('.scan-map-depth-btn'), function(b) {\n",
    "      b.classList.toggle('active', b.getAttribute('data-depth') === scanSelectedDepth);\n",
    "    });\n",
    "    Array.prototype.forEach.call(el.querySelectorAll('.scan-selected-depth-label'), function(span) { span.textContent = scanSelectedDepth; });\n",
    "    map.eachLayer(function(layer) {\n",
    "      if (!layer || !layer.options || typeof layer.setStyle !== 'function') return;\n",
    "      var site = layer.options.layerId;\n",
    "      if (site === undefined || site === null) return;\n",
    "      site = String(site);\n",
    "      var rec = scanMarkerLookup[site] && scanMarkerLookup[site][scanSelectedDepth];\n",
    "      if (!rec) return;\n",
    "      layer.setStyle({ fillColor: rec.fill || '#FFFFFF', fillOpacity: (rec.fillOpacity === undefined || rec.fillOpacity === null) ? 0.88 : rec.fillOpacity });\n",
    "      if (typeof layer.unbindTooltip === 'function' && typeof layer.bindTooltip === 'function') {\n",
    "        layer.unbindTooltip();\n",
    "        layer.bindTooltip(rec.hover || 'SCAN station', {className:'scan-sandbox-tooltip', direction:'auto', opacity:0.95});\n",
    "      }\n",
    "    });\n",
    "  }\n",
    "\n",
    "  if (!el._scanPopupDepthBound) {\n",
    "    map.on('popupopen', function(e) {\n",
    "      var root = e.popup && e.popup.getElement ? e.popup.getElement() : null;\n",
    "      scanSetPopupDepth(root, scanSelectedDepth);\n",
    "    });\n",
    "    el._scanPopupDepthBound = true;\n",
    "  }\n",
    "\n",
    "  if (!el.querySelector('.scan-depth-top-left-control')) {\n",
    "    var depthCtl = L.control({position: 'topleft'});\n",
    "    depthCtl.onAdd = function(mapObj) {\n",
    "      var div = L.DomUtil.create('div', 'scan-depth-top-left-control leaflet-control');\n",
    "      div.innerHTML = ", depth_control_json, ";\n",
    "      L.DomEvent.disableClickPropagation(div);\n",
    "      L.DomEvent.disableScrollPropagation(div);\n",
    "      return div;\n",
    "    };\n",
    "    depthCtl.addTo(map);\n",
    "  }\n",
    "\n",
    "  if (!el.querySelector('.scan-legend-top-left-control')) {\n",
    "    var legendCtl = L.control({position: 'topleft'});\n",
    "    legendCtl.onAdd = function(mapObj) {\n",
    "      var div = L.DomUtil.create('div', 'scan-legend-top-left-control leaflet-control');\n",
    "      div.innerHTML = ", legend_json, ";\n",
    "      L.DomEvent.disableClickPropagation(div);\n",
    "      L.DomEvent.disableScrollPropagation(div);\n",
    "      return div;\n",
    "    };\n",
    "    legendCtl.addTo(map);\n",
    "  }\n",
    "\n",
    "  if (!el._scanMapDepthButtonsBound) {\n",
    "    el.addEventListener('click', function(e) {\n",
    "      var btn = e.target.closest ? e.target.closest('.scan-map-depth-btn') : null;\n",
    "      if (!btn) return;\n",
    "      scanApplyDepth(btn.getAttribute('data-depth'));\n",
    "    });\n",
    "    el._scanMapDepthButtonsBound = true;\n",
    "  }\n",
    "\n",
    "  scanApplyDepth(scanSelectedDepth);\n",
    "}\n"
  )
)

# ==== 8. Write standalone HTML ==============================================

if (!dir.exists(dirname(OUT_HTML))) {
  dir.create(dirname(OUT_HTML), recursive = TRUE, showWarnings = FALSE)
}

htmlwidgets::saveWidget(m, OUT_HTML, selfcontained = TRUE)

message("Wrote SCAN popup sandbox HTML: ", OUT_HTML)
message("Stations shown: ", nrow(latest))
message("Symbol / initial popup depth: ", PLOT_DEPTH_IN, " in")
message("Open the timestamped HTML in a browser and click several SCAN stations to compare popup layouts.")
