# ==== 20_build_external_service_catalog.r =====================================
##
## PURPOSE:
##   Maintain the approved external-overlay service catalog used by the
##   PortaTreasure2 Tools / External Overlays panel.
##
## OUTPUT:
##   00_config/external_service_catalog.csv
##
## DESIGN:
##   This version writes a curated approved catalog.  Later versions can add
##   source-specific harvesters that write broad candidate lists to
##   04_processed_data/qa/ for manual review before approved rows are promoted.
##

suppressPackageStartupMessages({
  library(readr)
  library(tibble)
  library(dplyr)
})

WRITE_APPROVED_CATALOG <- TRUE

catalog_path <- file.path("00_config", "external_service_catalog.csv")

approved_catalog <- tibble::tribble(
  ~agency, ~program, ~theme, ~display_name, ~service_type, ~service_url,
  ~supports_popups, ~default_clickable, ~default_opacity, ~notes, ~source_page,
  ~priority, ~default_load_mode, ~where_clause, ~large_layer_warning,
  ~min_zoom_live, ~min_zoom_current_view, ~legend_url, ~legend_note,
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater", "DWR Groundwater Depth Seasonal Contours", "map", "https://utility.arcgis.com/usrsvcs/servers/15e2bef61bdb4cabb2719c3147211049/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Contours/MapServer/0", "FALSE", "FALSE", "0.60", "Seasonal groundwater-depth contours. Service may be proxied through utility.arcgis.com.", "https://data.cnra.ca.gov/dataset/i08-groundwaterdepthseasonal-contours", "30", "visual", "", "", "8", "", "https://utility.arcgis.com/usrsvcs/servers/15e2bef61bdb4cabb2719c3147211049/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Contours/MapServer/legend", "DWR service legend; symbols may vary by scale or service configuration.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater / SGMA", "DWR Adjudicated Groundwater Areas", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Adjudicated_Areas/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Adjudicated_Areas/MapServer", "110", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Adjudicated_Areas/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater / SGMA", "DWR Groundwater Sustainability Agencies", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Agencies/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Agencies/MapServer", "111", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Agencies/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater / SGMA", "DWR Groundwater Sustainability Plan Areas", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Plan_Areas/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Plan_Areas/MapServer", "112", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Groundwater_Sustainability_Plan_Areas/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Hydrologic boundaries", "DWR Hydrologic Regions", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Hydrologic_Regions/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Hydrologic_Regions/MapServer", "113", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Hydrologic_Regions/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Planning / water management", "DWR Water Plan Planning Areas", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Water_Plan_Planning_Areas/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Water_Plan_Planning_Areas/MapServer", "114", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Water_Plan_Planning_Areas/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Planning / water management", "DWR IRWM Regions", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_IRWM_Regions/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_IRWM_Regions/MapServer", "115", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_IRWM_Regions/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Water agencies / districts", "DWR Water Districts", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_WaterDistricts/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_WaterDistricts/MapServer", "116", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_WaterDistricts/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Water infrastructure / regulation", "DWR FERC Project Boundaries", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_FERCBoundaries/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_FERCBoundaries/MapServer", "117", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_FERCBoundaries/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Delta / Bay-Delta", "DWR Delta Primary/Secondary Zones", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Delta_PrimarySecondary_Zones/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Delta_PrimarySecondary_Zones/MapServer", "118", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Delta_PrimarySecondary_Zones/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Delta / Bay-Delta", "DWR Legal Delta Boundary", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_LegalDeltaBoundary/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_LegalDeltaBoundary/MapServer", "119", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_LegalDeltaBoundary/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Delta / Bay-Delta", "DWR Suisun Marsh Boundary", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SuisunMarshBoundary/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SuisunMarshBoundary/MapServer", "120", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SuisunMarshBoundary/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Flood management", "DWR SPFC Planning Area", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SPFCPlanningArea_20100301/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SPFCPlanningArea_20100301/MapServer", "121", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SPFCPlanningArea_20100301/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Flood management", "DWR Systemwide Planning Area", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SystemwidePA_20101007/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SystemwidePA_20101007/MapServer", "122", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_SystemwidePA_20101007/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Flood management", "DWR Local Maintenance Areas \u2014 Flood Protection", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Local_Maintenance_Areas_Flood_Protection/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Local_Maintenance_Areas_Flood_Protection/MapServer", "123", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Local_Maintenance_Areas_Flood_Protection/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Planning / water management", "DWR Proposition 1 Funding Areas", "map", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Proposition1_Funding_Areas/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Proposition1_Funding_Areas/MapServer", "124", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_Proposition1_Funding_Areas/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater basins", "DWR Bulletin 118 Groundwater Basins", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_CA_GroundwaterBasins/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_CA_GroundwaterBasins/MapServer", "130", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_CA_GroundwaterBasins/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater / SGMA", "DWR Critically Overdrafted Basins", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_CriticallyOverdraftedBasins/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_CriticallyOverdraftedBasins/MapServer", "131", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_CriticallyOverdraftedBasins/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater / SGMA", "DWR SGMA 2019 Basin Prioritization", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_SGMA_2019_Basin_Prioritization/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_SGMA_2019_Basin_Prioritization/MapServer", "132", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_B118_SGMA_2019_Basin_Prioritization/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Depth Contours", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Contours/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Contours/MapServer", "133", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Contours/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Depth Points", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Points/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Points/MapServer", "134", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterDepthSeasonal_Points/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Elevation Contours", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Contours/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Contours/MapServer", "135", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Contours/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Elevation Points", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Points/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Points/MapServer", "136", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterElevationSeasonal_Points/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Level Change Contours", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Contours/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Contours/MapServer", "137", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Contours/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater levels", "DWR Seasonal Groundwater Level Change Points", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Points/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Points/MapServer", "138", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterLevelChangeSeasonal_Points/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater monitoring", "DWR Groundwater Stations \u2014 Enterprise Water Management", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterStations_EnterpriseWaterManagement/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterStations_EnterpriseWaterManagement/MapServer", "139", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterStations_EnterpriseWaterManagement/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Water quality / monitoring", "DWR Discrete Grab Water Quality Stations", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Discrete_Grab_Water_Quality/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Discrete_Grab_Water_Quality/MapServer", "140", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Discrete_Grab_Water_Quality/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Water quality / monitoring", "DWR Continuous Monitoring Stations \u2014 Hydstra Period", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Monitoring_Continuous_Hydstra_Period/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Monitoring_Continuous_Hydstra_Period/MapServer", "141", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_Stations_Monitoring_Continuous_Hydstra_Period/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Groundwater Head Observations", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Groundwater_Head_Observations/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Groundwater_Head_Observations/MapServer", "142", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Groundwater_Head_Observations/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Stream Observations", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Stream_Observations/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Stream_Observations/MapServer", "143", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Stream_Observations/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Subsidence Observations", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Subsidence_Observations/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Subsidence_Observations/MapServer", "144", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/C2VSimFG_Subsidence_Observations/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Boundary", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Boundary/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Boundary/MapServer", "145", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Boundary/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Elements", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Elements/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Elements/MapServer", "146", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Elements/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Nodes", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Nodes/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Nodes/MapServer", "147", "visual", "", "", "9", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Nodes/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Stream Reaches", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Stream_Reaches/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Stream_Reaches/MapServer", "148", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Stream_Reaches/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater models / C2VSim", "DWR C2VSimFG Subregions", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Subregions/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Subregions/MapServer", "149", "visual", "", "", "", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_C2VSimFG_Subregions/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Geology / infrastructure", "DWR Fault Crossings \u2014 State Water Project", "map", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_FaultCrossings_StateWaterProject/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_FaultCrossings_StateWaterProject/MapServer", "150", "visual", "", "", "9", "", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_FaultCrossings_StateWaterProject/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Drought / water shortage vulnerability", "DWR Water Shortage Social Vulnerability \u2014 Block Groups", "map", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Social_Vulnerability_BlockGroups/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Social_Vulnerability_BlockGroups/MapServer", "160", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Social_Vulnerability_BlockGroups/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Drought / water shortage vulnerability", "DWR Water Shortage Vulnerability \u2014 Sections", "map", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Sections/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Sections/MapServer", "161", "visual", "", "", "9", "", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Sections/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Drought / water shortage vulnerability", "DWR Water Shortage Vulnerability \u2014 Small Water Systems", "map", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Small_Water_Systems/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Small_Water_Systems/MapServer", "162", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_Water_Shortage_Vulnerability_Small_Water_Systems/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Wells / well completion reports", "DWR Well Completion Reports Index", "map", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_WellCompletionReports/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_WellCompletionReports/MapServer", "163", "visual", "", "", "10", "", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_WellCompletionReports/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Conveyance / infrastructure", "DWR Local Canals and Aqueducts", "map", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Canals_and_Aqueducts_local/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Canals_and_Aqueducts_local/MapServer", "170", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Canals_and_Aqueducts_local/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Flood management / levees", "DWR Historic Levee Breaks", "map", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Levee_Breaks_Historic/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Levee_Breaks_Historic/MapServer", "171", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_Levee_Breaks_Historic/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Water operations / CalSim", "DWR CalSim II Inflow Data Locations", "map", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_CalSimII_InflowData/MapServer", "FALSE", "FALSE", "0.58", "California DWR ArcGIS REST MapServer layer. Use as a visual overlay.", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_CalSimII_InflowData/MapServer", "172", "visual", "", "", "8", "", "https://gis.water.ca.gov/arcgis/rest/services/InlandWaters/i12_CalSimII_InflowData/MapServer/legend", "DWR service-rendered legend.",
  "DWR / CNRA", "DWR GIS Atlas", "Wells / well completion reports", "DWR Well Completion Reports Index \u2014 inspectable features", "feature", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_WellCompletionReports/FeatureServer/0", "TRUE", "TRUE", "0.75", "California DWR FeatureServer layer. Current-view loading is recommended for larger statewide layers.", "https://gis.water.ca.gov/arcgis/rest/services/Environment/i07_WellCompletionReports/FeatureServer/0", "180", "current_view", "", "Potentially large statewide FeatureServer. Zoom in first and use current-view loading for better performance.", "10", "10", "", "",
  "DWR / CNRA", "DWR GIS Atlas", "Water agencies / districts", "DWR Water Districts \u2014 inspectable features", "feature", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_WaterDistricts/FeatureServer/0", "TRUE", "TRUE", "0.75", "California DWR FeatureServer layer. Current-view loading is recommended for larger statewide layers.", "https://gis.water.ca.gov/arcgis/rest/services/Boundaries/i03_WaterDistricts/FeatureServer/0", "181", "current_view", "", "Potentially large statewide FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "DWR / CNRA", "DWR GIS Atlas", "Groundwater monitoring", "DWR Groundwater Stations \u2014 inspectable features", "feature", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterStations_EnterpriseWaterManagement/FeatureServer/0", "TRUE", "TRUE", "0.75", "California DWR FeatureServer layer. Current-view loading is recommended for larger statewide layers.", "https://gis.water.ca.gov/arcgis/rest/services/Geoscientific/i08_GroundwaterStations_EnterpriseWaterManagement/FeatureServer/0", "182", "current_view", "", "Potentially large statewide FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "8", "", "",
  "DWR / CNRA", "California's Groundwater Live", "Groundwater levels", "DWR Recently Measured Groundwater Levels", "feature", "https://services.arcgis.com/aa38u6OgfNoCkTJ6/arcgis/rest/services/GWL_Recently_Measured_v3/FeatureServer/0", "TRUE", "TRUE", "0.75", "Monitoring wells in DWR's groundwater elevation database with a groundwater elevation measurement reported in the last 18 months.", "https://catalog.data.gov/dataset/californias-groundwater-live-supporting-data-eb38d/resource/15dcd342-e4e5-4a1c-b766-a417d373470c", "183", "current_view", "", "Statewide point FeatureServer. Current-view loading is recommended for performance.", "8", "8", "", "",
  "SWRCB / Water Boards", "Water Rights", "Water rights / PODs", "SWRCB Points of Diversion", "map", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Rights/Points_of_Diversion/MapServer", "FALSE", "FALSE", "0.58", "SWRCB Points of Diversion MapServer from WRIMS-derived locations. PT2 also has a local filtered POD/WR layer.", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Rights/Points_of_Diversion/MapServer?f=pjson", "210", "visual", "", "", "8", "", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Rights/Points_of_Diversion/MapServer/legend", "",
  "SWRCB / Water Boards", "Integrated Report", "Water quality / impaired waters", "SWRCB Impaired Waters / Integrated Report", "map", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Quality/Impaired_waters/MapServer", "FALSE", "FALSE", "0.58", "Water bodies assessed and listed as impaired under Clean Water Act 303(d)/305(b).", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Quality/Impaired_waters/MapServer", "211", "visual", "", "", "8", "", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/Water_Quality/Impaired_waters/MapServer/legend", "",
  "SWRCB / Water Boards", "GAMA / Reference Boundaries", "Administrative / RWQCB", "RWQCB Boundaries \u2014 Water Boards", "map", "https://gispublic.waterboards.ca.gov/portalserver/rest/services/GAMA/Reference_Boundaries/MapServer/4", "FALSE", "FALSE", "0.58", "Regional Water Quality Control Board boundaries from Water Boards GAMA reference-boundaries service.", "https://gispublic.waterboards.ca.gov/portalserver/rest/services/GAMA/Reference_Boundaries/MapServer", "212", "visual", "", "", "", "", "https://gispublic.waterboards.ca.gov/portalserver/rest/services/GAMA/Reference_Boundaries/MapServer/legend", "",
  "SWRCB / Water Boards", "SAFER / Aquifer Risk", "Groundwater quality / drinking water", "Water Boards 2026 Aquifer Risk Map \u2014 Water Quality Risk", "feature", "https://gispublic.waterboards.ca.gov/portalserver/rest/services/Hosted/Water_Quality_Risk_2026_ARM/FeatureServer/2", "TRUE", "TRUE", "0.75", "Water quality risk estimates for domestic wells and state small water systems. Current-view loading is recommended.", "https://gispublic.waterboards.ca.gov/portalserver/rest/services/Hosted/Water_Quality_Risk_2026_ARM/FeatureServer", "213", "current_view", "", "Large statewide polygon FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "SWRCB / Water Boards", "SaveWater / public water systems", "Water service areas", "Water Boards Drought Water Service Areas", "map", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/webmap/Service_GISPublic/MapServer/0", "FALSE", "FALSE", "0.58", "Drought water service area boundaries used in SaveWater.ca.gov context.", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/webmap/Service_GISPublic/MapServer", "214", "visual", "", "", "8", "", "https://gispublic.waterboards.ca.gov/arcgis/rest/services/webmap/Service_GISPublic/MapServer/legend", "",
  "CDFW", "ACE / BIOS", "ACE / terrestrial biodiversity", "CDFW ACE Statewide Terrestrial Biodiversity Summary", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1331_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1331_fpu/FeatureServer/0", "300", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / species biodiversity", "CDFW ACE Species Biodiversity", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2769_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2769_fpu/FeatureServer/0", "301", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / rare species", "CDFW ACE Terrestrial Rare Species Richness", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1333_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1333_fpu/FeatureServer/0", "302", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / irreplaceability", "CDFW ACE Terrestrial Irreplaceability Summary", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1334_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds1334_fpu/FeatureServer/0", "303", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / aquatic biodiversity", "CDFW ACE Aquatic Native Species Richness Summary", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2743_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2743_fpu/FeatureServer/0", "304", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / aquatic biodiversity", "CDFW ACE Aquatic Native Amphibian Richness", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2746_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2746_fpu/FeatureServer/0", "305", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / aquatic biodiversity", "CDFW ACE Aquatic Amphibian Irreplaceability", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2754_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2754_fpu/FeatureServer/0", "306", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / wetlands and riparian", "CDFW ACE Freshwater Wetlands by Watershed", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2764_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2764_fpu/FeatureServer/0", "307", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / wetlands and riparian", "CDFW ACE Riparian Habitat by Watershed", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2758_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2758_fpu/FeatureServer/0", "308", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / vegetation and habitat", "CDFW ACE Oak Woodlands", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2723_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2723_fpu/FeatureServer/0", "309", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / vegetation and habitat", "CDFW ACE Oak Shrublands", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2863_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2863_fpu/FeatureServer/0", "310", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / wetlands and riparian", "CDFW ACE Estuary and Tidal Habitat", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2860_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2860_fpu/FeatureServer/0", "311", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / species habitat", "CDFW ACE Monarch Overwintering Areas", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2861_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2861_fpu/FeatureServer/0", "312", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / climate vulnerability", "CDFW ACE Terrestrial Climate Vulnerable Species", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2701_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2701_fpu/FeatureServer/0", "313", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / game species", "CDFW ACE Terrestrial Native Game Species", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2702_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2702_fpu/FeatureServer/0", "314", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "CDFW", "ACE / BIOS", "ACE / birds", "CDFW ACE Terrestrial Rare Bird Richness", "feature", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2711_fpu/FeatureServer/0", "TRUE", "TRUE", "0.55", "CDFW Areas of Conservation Emphasis (ACE) FeatureServer. Current-view loading is recommended for these statewide layers.", "https://services2.arcgis.com/Uq9r85Potqm3MfRV/arcgis/rest/services/biosds2711_fpu/FeatureServer/0", "315", "current_view", "", "Large statewide CDFW ACE FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "BLM AIM", "AIM", "Monitoring / terrestrial", "BLM AIM LMF Hub", "feature", "https://services1.arcgis.com/KbxwQRRfWyEYLgp4/arcgis/rest/services/BLM_Natl_AIM_LMF_Hub/FeatureServer/0", "TRUE", "TRUE", "0.75", "BLM Assessment, Inventory, and Monitoring (AIM) public FeatureServer. Current-view loading is recommended.", "https://gbp-blm-egis.hub.arcgis.com/pages/aim", "400", "current_view", "", "Large national BLM AIM FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "BLM AIM", "AIM", "Monitoring / riparian / aquatic", "BLM AIM Lotic Indicators", "feature", "https://services1.arcgis.com/KbxwQRRfWyEYLgp4/arcgis/rest/services/BLM_Natl_AIM_Lotic_Indicators_Hub/FeatureServer/5", "TRUE", "TRUE", "0.75", "BLM Assessment, Inventory, and Monitoring (AIM) public FeatureServer. Current-view loading is recommended.", "https://gbp-blm-egis.hub.arcgis.com/pages/aim", "401", "current_view", "", "Large national BLM AIM FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "BLM AIM", "AIM", "Monitoring / terrestrial", "BLM AIM TerrADat", "feature", "https://services1.arcgis.com/KbxwQRRfWyEYLgp4/arcgis/rest/services/BLM_Natl_AIM_TerrADat_Hub/FeatureServer/0", "TRUE", "TRUE", "0.75", "BLM Assessment, Inventory, and Monitoring (AIM) public FeatureServer. Current-view loading is recommended.", "https://gbp-blm-egis.hub.arcgis.com/pages/aim", "402", "current_view", "", "Large national BLM AIM FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "BLM AIM", "AIM", "Monitoring / species indicators", "BLM AIM Terrestrial Species Indicators", "feature", "https://services1.arcgis.com/KbxwQRRfWyEYLgp4/arcgis/rest/services/BLM_Natl_AIM_Terrestrial_Species_Indicators_Public/FeatureServer/6", "TRUE", "TRUE", "0.75", "BLM Assessment, Inventory, and Monitoring (AIM) public FeatureServer. Current-view loading is recommended.", "https://gbp-blm-egis.hub.arcgis.com/pages/aim", "403", "current_view", "", "Large national BLM AIM FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "BLM GBP", "Surface Management Agency", "Federal lands / land status", "BLM CA Land Status / Surface Management Agency", "map", "https://gis.blm.gov/caarcgis/rest/services/lands/BLM_CA_LandStatus_SurfaceManagementAgency/MapServer/0", "FALSE", "FALSE", "0.58", "California surface management agency context layer. Treat as surface-management context, not parcel-level ownership.", "https://gbp-blm-egis.hub.arcgis.com/datasets/BLM-EGIS::blm-ca-land-status-surface-management-agency/about", "405", "visual", "", "", "", "", "https://gis.blm.gov/caarcgis/rest/services/lands/BLM_CA_LandStatus_SurfaceManagementAgency/MapServer/legend", "BLM SMA legend from the ArcGIS REST service.",
  "USFWS", "Ecological Services", "Threatened / endangered species", "USFWS Final Critical Habitat", "feature", "https://services.arcgis.com/QVENGdaPbd4LUkLV/arcgis/rest/services/USFWS_Critical_Habitat/FeatureServer/0", "TRUE", "TRUE", "0.45", "Final critical habitat features. Large national polygon layer; current-view loading is strongly recommended.", "https://gis-fws.opendata.arcgis.com/", "500", "current_view", "", "Large national critical-habitat FeatureServer. Zoom in first and use current-view loading for better performance.", "9", "9", "", "",
  "USFWS", "National Wetlands Inventory", "Wetlands / riparian", "USFWS National Wetlands Inventory", "feature", "https://services3.arcgis.com/nV0HyP5uKL48nAKr/arcgis/rest/services/NWIWetlands/FeatureServer/0", "TRUE", "TRUE", "0.45", "National Wetlands Inventory wetlands/deepwater habitats. Very large national layer; current-view loading is required for practical use.", "https://www.fws.gov/program/national-wetlands-inventory/web-mapping-services", "501", "current_view", "", "Very large national wetlands FeatureServer. Zoom in first and use current-view loading.", "10", "10", "", "",
  "FEMA", "NFHL", "Flood hazards", "FEMA NFHL Flood Hazard Zones", "map", "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28", "FALSE", "FALSE", "0.60", "Effective FEMA National Flood Hazard Layer flood hazard zones. Scale-dependent map layer.", "https://hazards.fema.gov/femaportal/wps/portal/NFHLWMS", "600", "visual", "", "", "10", "", "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/legend", "FEMA NFHL legend is service-rendered and may include multiple scale-dependent flood-hazard symbols.",
  "NOAA", "Digital Coast / Sea Level Rise Viewer", "Sea level rise / coastal flooding", "NOAA Sea Level Rise Inundation \u2014 1.5 ft", "map", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_1_5ft/MapServer", "FALSE", "FALSE", "0.55", "NOAA Digital Coast sea-level-rise screening layer. Use as visual context near the coast.", "https://coast.noaa.gov/digitalcoast/tools/slr.html", "700", "visual", "", "", "9", "", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_1_5ft/MapServer/legend", "NOAA service-rendered legend.",
  "NOAA", "Digital Coast / Sea Level Rise Viewer", "Sea level rise / coastal flooding", "NOAA Sea Level Rise Inundation \u2014 2 ft", "map", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_2ft/MapServer", "FALSE", "FALSE", "0.55", "NOAA Digital Coast sea-level-rise screening layer. Use as visual context near the coast.", "https://coast.noaa.gov/digitalcoast/tools/slr.html", "701", "visual", "", "", "9", "", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_2ft/MapServer/legend", "NOAA service-rendered legend.",
  "NOAA", "Digital Coast / Sea Level Rise Viewer", "Sea level rise / coastal flooding", "NOAA Sea Level Rise Inundation \u2014 3 ft", "map", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_3ft/MapServer", "FALSE", "FALSE", "0.55", "NOAA Digital Coast sea-level-rise screening layer. Use as visual context near the coast.", "https://coast.noaa.gov/digitalcoast/tools/slr.html", "702", "visual", "", "", "9", "", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_3ft/MapServer/legend", "NOAA service-rendered legend.",
  "NOAA", "Digital Coast / Sea Level Rise Viewer", "Sea level rise / coastal flooding", "NOAA Sea Level Rise Inundation \u2014 6 ft", "map", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_6ft/MapServer", "FALSE", "FALSE", "0.55", "NOAA Digital Coast sea-level-rise screening layer. Use as visual context near the coast.", "https://coast.noaa.gov/digitalcoast/tools/slr.html", "703", "visual", "", "", "9", "", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/slr_6ft/MapServer/legend", "NOAA service-rendered legend.",
  "NOAA", "Digital Coast / Sea Level Rise Viewer", "Sea level rise / coastal flooding", "NOAA Potential Marsh Distribution \u2014 6.5 ft", "map", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/marsh_650/MapServer", "FALSE", "FALSE", "0.55", "NOAA Digital Coast sea-level-rise screening layer. Use as visual context near the coast.", "https://coast.noaa.gov/digitalcoast/tools/slr.html", "704", "visual", "", "", "9", "", "https://www.coast.noaa.gov/arcgis/rest/services/dc_slr/marsh_650/MapServer/legend", "NOAA service-rendered legend.",
  "CNRA", "Ocean Protection / Coastal hazards", "Sea level rise / coastal flooding", "CNRA CSMW Potential Sea-Level-Rise Impacts", "map", "https://gis.cnra.ca.gov/arcgis/rest/services/Ocean/CSMW_Potential_Sea_Level_Rise_Impacts/MapServer", "FALSE", "FALSE", "0.55", "Potential sea-level-rise impact layers for California coastal screening.", "https://gis.cnra.ca.gov/arcgis/rest/services/Ocean/CSMW_Potential_Sea_Level_Rise_Impacts/MapServer", "710", "visual", "", "", "8", "", "https://gis.cnra.ca.gov/arcgis/rest/services/Ocean/CSMW_Potential_Sea_Level_Rise_Impacts/MapServer/legend", ""
) |>
  dplyr::mutate(priority = suppressWarnings(as.numeric(priority))) |>
  dplyr::arrange(priority, agency, theme, display_name)

if (WRITE_APPROVED_CATALOG) {
  dir.create(dirname(catalog_path), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(approved_catalog, catalog_path)

  message("Approved external overlay service catalog written:")
  message("  ", catalog_path)
  message("Rows: ", nrow(approved_catalog))
}
