'use strict';
// Offline DOM/event doubles execute the actual production components. No layout,
// native hit testing, browser paint or assistive-technology acceptance is claimed.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const base=path.resolve(__dirname,'..');
const UI=require('../03_functions/js/soil_moisture_ui.js'),Charts=require('../03_functions/js/soil_moisture_charts.js');
const E=require('../03_functions/js/soil_moisture_engine.js'),D=require('../03_functions/js/soil_moisture_depths.js'),T=require('../03_functions/js/soil_moisture_transport.js');
const Core=require('../03_functions/js/dendra_core.js'),Contract=require('../03_functions/js/dendra_reader.js');
const decode=s=>String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
class Element {
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.attributes={};this.listeners={};this.style={};this.dataset={};this.hidden=false;this.validity={badInput:false};this._text='';this.classList={contains:c=>(this.attributes.class||'').split(' ').includes(c),add:c=>{if(!this.classList.contains(c))this.setAttribute('class',(this.attributes.class||'')+' '+c);},remove:c=>this.setAttribute('class',(this.attributes.class||'').split(/\s+/).filter(x=>x!==c).join(' ')),toggle:(c,on)=>{const enabled=on??!this.classList.contains(c);this.classList[enabled?'add':'remove'](c);return enabled;}};}
  setAttribute(k,v){this.attributes[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);if(k==='checked')this.checked=true;if(k==='disabled')this.disabled=true;}
  getAttribute(k){return this.attributes[k]??null;}hasAttribute(k){return k in this.attributes;}
  set className(v){this.setAttribute('class',v);}get className(){return this.attributes.class||'';}
  set id(v){this.setAttribute('id',v);}get id(){return this.attributes.id;}
  get type(){return this.attributes.type||'';}
  set value(v){this._value=String(v);}get value(){return this._value??this.attributes.value??(this.tagName==='SELECT'?(this.querySelector('option[selected]')||this.querySelector('option'))?.value:'')??'';}
  appendChild(x){x.parentNode=this;this.children.push(x);return x;}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);}
  matches(selector){const tag=selector.match(/^[a-zA-Z][\w-]*/)?.[0];if(tag&&this.tagName!==tag.toUpperCase())return false;for(const [,c] of selector.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(c))return false;const id=selector.match(/#([\w-]+)/)?.[1];if(id&&this.id!==id)return false;for(const [,k,v1,v2] of selector.matchAll(/\[([^=\]]+)(?:=["']?([^"'\]]*)["']?)?\]/g)){const v=v1??v2;if(!this.hasAttribute(k)||v!==undefined&&this.getAttribute(k)!==v)return false;}return true;}
  querySelectorAll(selector){if(selector.includes(' ')){const [first,...rest]=selector.split(' ');return this.querySelectorAll(first).flatMap(n=>n.querySelectorAll(rest.join(' ')));}const out=[];for(const child of this.children){if(child.matches(selector))out.push(child);out.push(...child.querySelectorAll(selector));}return out;}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}closest(s){return this.matches(s)?this:this.parentNode?.closest(s)||null;}
  get nextElementSibling(){return this.parentNode?.children[this.parentNode.children.indexOf(this)+1];}get previousElementSibling(){return this.parentNode?.children[this.parentNode.children.indexOf(this)-1];}
  set textContent(v){this.children=[];this._text=String(v);}get textContent(){return decode(this._text+this.children.map(c=>c.textContent).join(''));}
  set innerHTML(html){this.children=[];this._text='';const stack=[this],voids=new Set(['INPUT','BR','HR','IMG','META','LINK']);for(const token of String(html).match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){if(stack.length>1)stack.pop();}else if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const el=new Element(tag);for(const [,key,,quoted,single,bare] of token.slice(tag.length+1,-1).matchAll(/([\w:-]+)(?:\s*=\s*((?:"([^"]*)")|(?:'([^']*)')|([^\s>]+)))?/g))el.setAttribute(key,decode(quoted??single??bare??''));stack.at(-1).appendChild(el);if(!voids.has(el.tagName)&&!token.endsWith('/>'))stack.push(el);}else stack.at(-1)._text+=token;}}
  get innerHTML(){return this._text+this.children.map(c=>'<'+c.tagName.toLowerCase()+' '+Object.entries(c.attributes).map(([k,v])=>k+'="'+v+'"').join(' ')+'>'+c.innerHTML+'</'+c.tagName.toLowerCase()+'>').join('');}
  addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}removeEventListener(type,fn){this.listeners[type]=(this.listeners[type]||[]).filter(x=>x!==fn);}
  dispatch(type,extra={}){const e={type,target:this,stopped:false,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...extra};let n=this;while(n){n['on'+type]?.(e);for(const fn of n.listeners[type]||[])fn(e);if(e.stopped)break;n=n.parentNode;}return e;}
  click(){if(!this.disabled)this.dispatch('click');}focus(){this.dispatch('focus');}getBoundingClientRect(){return {left:0,top:0,width:650,height:215};}
}
function environment(fixture,sourceRoot=base){
  const document=new Element('document');document.head=document.appendChild(new Element('head'));document.body=document.appendChild(new Element('body'));document.createElement=t=>new Element(t);document.getElementById=id=>document.querySelector('#'+id);
  const container=document.body.appendChild(new Element('div'));container.className='leaflet-container';
  const handlers={},map={getContainer:()=>container,controls:[],layers:new Set(),on(e,f){for(const t of e.split(' '))(handlers[t]??=[]).push(f);},off(e,f){handlers[e]=(handlers[e]||[]).filter(x=>x!==f);},emit(e,x){for(const f of handlers[e]||[])f(x);},hasLayer(l){return this.layers.has(l);},removeLayer(l){this.layers.delete(l);l.onRemove?.(this);},removeControl(c){this.controls=this.controls.filter(x=>x!==c);c.el?.remove();},fitBounds(){},closePopup(p=this.popup){if(p){this.emit('popupclose',{popup:p});if(this.popup===p)this.popup=null;}}};
  class Group {constructor(){this.items=[];}onAdd(m){this._map=m;}onRemove(){}on(){}addTo(m){if(m instanceof Group){m.items.push(this);this.onAdd(m._map);}else{m.layers.add(this);this.onAdd(m);}return this;}addLayer(l){this.items.push(l);}removeLayer(l){this.items=this.items.filter(x=>x!==l);}hasLayer(l){return this.items.includes(l);}clearLayers(){this.items=[];}}
  const L={layerGroup:()=>new Group(),LayerGroup:Group,DomUtil:{create:(tag,cls)=>{const e=new Element(tag);e.className=cls;return e;}},DomEvent:{disableClickPropagation(){},disableScrollPropagation(){}},control:()=>({addTo(m){this.el=this.onAdd(m);m.controls.push(this);document.body.appendChild(this.el);return this;},getContainer(){return this.el;}}),popup:options=>({options,getElement(){if(!this.el){this.el=new Element('div');this.el.className='leaflet-popup '+(this.options.className||'');if(this.content)this.el.appendChild(this.content);}return this.el;},setLatLng(){return this;},setContent(c){this.content=c;return this;},openOn(m){m.closePopup();this._map=m;m.popup=this;m.emit('popupopen',{popup:this});return this;},isOpen(){return this._map?.popup===this;},update(){}}),divIcon:options=>({options}),marker:(xy,options)=>({xy,options,events:{},el:new Element('div'),on(type,fn){for(const t of type.split(' '))(this.events[t]??=[]).push(fn);return this;},off(){this.events={};return this;},fire(type){for(const fn of this.events[type]||[])fn({target:this});return this;},getElement(){return this.el;},setIcon(icon){this.options.icon=icon;return this;},bindTooltip(t){this.tooltip=t;return this;},getTooltip(){return this.tooltip;},setTooltipContent(t){this.tooltip=t;return this;},openTooltip(){this.tooltipOpen=true;this.fire('tooltipopen');return this;},closeTooltip(){this.tooltipOpen=false;this.fire('tooltipclose');return this;},unbindTooltip(){this.closeTooltip();this.tooltip=null;return this;},addTo(g){g.addLayer(this);return this;}})};
  const requests=[],fetcher=async url=>{const u=new URL(url);assert.equal(u.hostname,'saved.invalid');let rel=u.pathname.replace(/^\/(?:docs\/data\/)?/,'');requests.push(rel);return new Response(fs.readFileSync(path.join(fixture,rel)));};
  const closeout={actionsHtml:()=>'<button class="sm-dock">Dock</button><button class="sm-close">Close</button>',wire(card,selector,fn){card.querySelector(selector).onclick=()=>{card.style.display='none';fn();};},makeDetachable:()=>({destroy(){}}),scheduleLayout(){}};
  const window={innerWidth:1280,innerHeight:800,DendraCore:Core,BrimDendraReader:{...Contract,Reader:class extends Contract.Reader{constructor(url){super(url,fetcher,crypto.webcrypto);}}},BRIM:{soilMoistureUI:UI,soilMoistureCharts:Charts,soilMoistureDepths:D,soilMoistureEngine:E,soilMoistureTransport:T,legendCloseout:closeout}};
  const context=vm.createContext({window,document,map,L,URL,location:{href:'http://saved.invalid/'},performance,Date,structuredClone,AbortController,fetch:fetcher,crypto:crypto.webcrypto,TextDecoder,TextEncoder,Blob,setTimeout,clearTimeout,setInterval:()=>1,clearInterval(){},setOpsLayerLoading(){},recordStatus(){},DENDRA_DAILY_INDEX_URL:'http://saved.invalid/dendra/index.json'});
  vm.runInContext(fs.readFileSync(path.join(sourceRoot,'03_functions/js/dendra_layer.js'),'utf8'),context);
  return {context,window,document,map,L,fetcher,requests,run:code=>vm.runInContext(code,context)};
}
async function until(fn){for(let i=0;i<300;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw Error('Offline component did not settle');}
function scanAdapter(env){const src=fs.readFileSync(path.join(base,'03_functions/leaflet_ops_live_scan_helpers.r'),'utf8');const raw=src.slice(src.indexOf('r"---(')+6,src.lastIndexOf(')---"'));vm.runInContext(raw,env.context);}
async function main(){
  assert(process.argv[2],'Pass verified saved data directory');const fixture=path.resolve(process.argv[2]),checks=[];
  const pre=process.env.BRIM_SOIL_START_SOURCE;assert(pre,'BRIM_SOIL_START_SOURCE must bind the actual pre-edit candidate');
  const snapshots=[];
  for(const [version,root] of [['before',pre],['after',base]]){
    const env=environment(fixture,root),reader=new Contract.Reader('http://saved.invalid/dendra/index.json',env.fetcher,crypto.webcrypto);await reader.loadIndex();env.context.reader=reader;const layer=env.run("makeDendraLayer({name:'dendra',reader,popupOnly:true})");layer.addTo(env.map);await until(()=>layer.dendra.active);const st=reader.index.stations.find(s=>s.source_name==='Camp Cady WA'||s.name==='Camp Cady WA');assert(st);layer.dendra.state.choices[st.station_id]='63531a67a9b61453fa1ca4ed';layer.dendra.openStation(st.station_id);await until(()=>env.map.popup?.content.querySelector('[data-overview] svg'));
    let box=env.map.popup.content;const snapshot={version,sensors:reader.index.streams.length,latest:box.querySelector('.latest-point').attributes,historyPaths:box.querySelector('[data-overview]').querySelectorAll('.data-trace').length,yearPaths:box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').length};
    assert.equal(snapshot.latest['data-date'],'2026-09-19');assert.equal(+snapshot.latest['data-value'],43.4152083333333);
    const shallow=reader.index.streams.find(s=>s.datastream_id==='63531a67a9b61453fa1ca4ed'),rows=await reader.history(reader.index,shallow);assert.equal(snapshot.historyPaths,Core.segments(rows).length);
    box.querySelector('[data-years="current"]').click();assert(box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').every(p=>p.getAttribute('data-wy')==='2026'));
    box.querySelector('[data-years="all"]').click();assert(box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').some(p=>+p.getAttribute('data-wy')<2026));
    box.querySelector('[data-years="recent"]').click();assert.deepEqual([...new Set(box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').map(p=>+p.getAttribute('data-wy')))].sort(),[...new Set(rows.filter(Core.good).map(r=>r.wy))].sort().slice(-3));
    box.querySelector('[data-years="all"]').click();const year=box.querySelector('[data-year]');year.click();assert(!box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').some(p=>p.getAttribute('data-wy')===year.dataset.year));year.click();
    const point=box.querySelector('[data-overview] .latest-point');box.querySelector('[data-overview] .hover-hit').dispatch('mousemove',{clientX:+point.getAttribute('cx'),clientY:+point.getAttribute('cy')});assert(box.querySelector('[data-overview] .chart-hover').textContent.includes('DOWY 354'));assert(box.querySelector('[data-overview] .chart-hover').textContent.includes('first-to-last span'));

    box.querySelector('[data-scale]').value='absolute';box.querySelector('[data-scale]').dispatch('change');assert(box.querySelector('[data-seasonal]').textContent.includes('100'));
    box.querySelector('[data-history="all"]').click();await until(()=>env.map.popup.content.querySelector('[data-overview] svg'));box=env.map.popup.content;
    const deeper=box.querySelector('[data-sensor-choice="63531a684b24f740d53623e6"]');assert(deeper);deeper.click();await until(()=>env.map.popup.content.querySelector('.latest-point')?.getAttribute('data-value')==='57.3468055555556');box=env.map.popup.content;
    if(version==='after'){const count=env.requests.length;box.querySelector('[data-dendra-view="history"]').click();box.querySelector('[data-dendra-view="years"]').click();assert.equal(env.requests.length,count);assert(box.querySelector('[data-selected-heading]').textContent.includes('Viewing: 60 cm'));assert(box.querySelector('[data-selected-heading]').textContent.includes('Map: 20 cm'));assert.equal(box.querySelector('[data-sensor-choice="63531a684b24f740d53623e6"]').getAttribute('aria-pressed'),'true');}
    box.querySelector('[data-param="soil_temperature"]').click();await until(()=>env.map.popup.content.querySelector('[data-overview] svg'));box=env.map.popup.content;assert(box.textContent.includes('No matching temperature for 60 cm'));assert(box.textContent.includes('20 cm'));
    assert.equal(layer.dendra.state.parameter,'soil_temperature');const temp=reader.index.streams.find(s=>s.parameter==='soil_temperature');const tempRows=await reader.history(reader.index,temp);assert.equal(+box.querySelector('.latest-point').getAttribute('data-value'),tempRows.filter(r=>r.ok).at(-1).v);
    if(version==='after'){assert(box.querySelector('[data-selected-heading]').textContent.includes(UI.fahrenheit(tempRows.filter(r=>r.ok).at(-1).v).toFixed(2)+' °F'));assert(!box.textContent.includes('Temperature companion available'));assert(box.querySelector('[data-overview]').textContent.includes('Temperature (°F)'));assert(box.querySelector('[data-overview]').textContent.includes(Charts.dateTicks(tempRows[0].date,tempRows.at(-1).date)[0].label));const hit=box.querySelector('.hover-hit');hit.focus();assert(box.querySelector('.chart-hover').textContent.includes(UI.fahrenheit(tempRows.filter(r=>r.ok).at(-1).v).toFixed(2)+' °F'));assert(box.querySelector('.chart-hover').textContent.includes('valid expected samples'));hit.dispatch('keydown',{key:'Home'});assert(box.querySelector('.chart-hover').textContent.includes(tempRows.filter(r=>r.ok)[0].date));}
    let csvId=null,csvText=null;const original=reader.csv.bind(reader);reader.csv=async(i,s,signal)=>{const text=await original(i,s,signal);csvId=s.datastream_id;csvText=text;return text;};box.querySelector('[data-csv]').click();await until(()=>csvId!==null);assert.equal(csvId,temp.datastream_id);assert.equal(csvText.trim().split('\n').length,temp.summary.calendar_row_count+1);snapshot.selectedTemperatureCsvSha256=crypto.createHash('sha256').update(csvText).digest('hex');
    const unknown=reader.index.streams.find(s=>s.datastream_id==='5d8e42e72da5c3cc53f6531d');layer.dendra.openStation(unknown.station_id);await until(()=>env.map.popup.content.querySelector('[data-overview] svg'));box=env.map.popup.content;assert(box.textContent.toLowerCase().includes('unspecified'));assert.equal(box.querySelector('.latest-point').getAttribute('data-date'),'2026-09-18');snapshot.unknownDepthLatest=box.querySelector('.latest-point').getAttribute('data-value');
    layer.forceRemove(env.map);assert.equal(layer.dendra.active,false);assert.equal(layer.dendra.popupOpen,false);snapshots.push(snapshot);
  }
  assert.equal(snapshots[0].historyPaths,snapshots[1].historyPaths);assert.equal(snapshots[0].yearPaths,snapshots[1].yearPaths);assert.equal(snapshots[0].selectedTemperatureCsvSha256,snapshots[1].selectedTemperatureCsvSha256);assert.equal(snapshots[0].unknownDepthLatest,snapshots[1].unknownDepthLatest);checks.push('actual before/after dendra components: history segment count, latest precision/date, full prior WYs, shortcuts, scale, archive, two sensors, temperature pairing, selected CSV, teardown');
  const env=environment(fixture);scanAdapter(env);vm.runInContext(fs.readFileSync(path.join(base,'03_functions/js/soil_moisture_controller.js'),'utf8'),env.context);const api=env.run('createSoilMoistureController()');for(const k of ['scan','dendra','snotel'])api.register(k,k,'/'+k+'.json');env.window.ptOpsActivateLayerByName=k=>api.sources[k].layer.addTo(env.map);env.window.ptOpsDeactivateLayerByName=k=>env.map.removeLayer(api.sources[k].layer);
  api.sources.snotel.layer.addTo(env.map);await until(()=>api.sources.snotel.index);api.redraw();await api.select('snotel:356:CA:SNTL');assert(env.map.getContainer().classList.contains('sm-popup-priority'));assert(env.document.body.classList.contains('sm-popup-priority'));let box=env.map.popup.content;assert(box.querySelector('[data-source-chart] svg'));assert(box.querySelector('.sm-headline').textContent.includes('3.9%'));assert(box.querySelector('[data-source-support]').textContent.includes('90 valid / 90 retained daily'));box.querySelector('[data-sensor-choice="SMS:-20:1"]').click();assert(box.querySelector('.sm-headline').textContent.includes('2%'));assert(box.textContent.includes('Map: 8 in · Viewing: 20 in'));assert.equal(box.querySelector('.latest-point').getAttribute('data-value'),'2');const csv=decodeURIComponent(box.querySelector('[data-csv]').href.split(',').slice(1).join(','));assert(csv.includes('2026-09-20'));assert(box.querySelector('[data-csv]').getAttribute('download').includes('SMS:-20:1'));
  checks.push('actual SNOTEL controller popup: Blue Lakes 8/20 heading/trace/export selection; map sensor stays 8in');
  api.sources.scan.layer.addTo(env.map);await until(()=>api.sources.scan.index);api.redraw();await api.select('scan:2191:CA:SCAN');assert(env.map.getContainer().classList.contains('sm-popup-priority'));box=env.map.popup.content;assert.equal(box.querySelector('[data-chart-view="years"]').getAttribute('aria-pressed'),'true');box.querySelector('[data-chart-view="history"]').click();assert(box.textContent.includes('Monthly record'));box.querySelector('[data-chart-view="years"]').click();assert(box.textContent.includes('Underlying reference-year traces not included'));assert(box.querySelector('[data-band="p00-p10"]'));assert(box.querySelector('[data-band="p90-p100"]'));const beforeRequests=env.requests.length;box.querySelector('[data-chart-band="traces"]').click();assert(!box.querySelector('[data-band="p00-p10"]'));box.querySelector('[data-chart-band="both"]').click();assert(box.querySelector('[data-band="p00-p10"]'));assert.equal(env.requests.length,beforeRequests);
  const activationRequests=env.requests.length;api.sources.dendra.layer.addTo(env.map);await until(()=>api.sources.dendra.index);assert.equal(env.requests.length-activationRequests,3);const metadata=api.sources.dendra.index.stations.find(st=>st.coordinates&&st.sensors.every(s=>!s.history));assert(metadata);api.redraw();const beforeMetadata=env.requests.length;await api.select(metadata.key);assert(env.map.popup.content.textContent.includes('Metadata-only'));assert.equal(env.requests.length,beforeMetadata);api.reset();assert.equal(api.stats().listeners,0);assert.equal(api.stats().markers,0);assert.equal(api.stats().card,false);assert(!env.map.getContainer().classList.contains('sm-popup-priority'));assert(!env.document.body.classList.contains('sm-popup-priority'));
  // Reuse the same controller after Clear All; the one map-level presentation
  // binding must still own later native dendra popups and release on close.
  api.sources.dendra.layer.addTo(env.map);await until(()=>api.sources.dendra.renderer?.dendra.active);const cady=api.sources.dendra.index.stations.find(st=>st.name==='Camp Cady WA');await api.select(cady.key);assert(env.map.getContainer().classList.contains('sm-popup-priority'));env.map.closePopup();assert(!env.map.getContainer().classList.contains('sm-popup-priority'));assert(!env.document.body.classList.contains('sm-popup-priority'));api.reset();env.map.emit('unload',{});
  checks.push('shared presentation priority attaches to actual SNOTEL/SCAN and reactivated dendra, clears on normal close/reset/unload; no browser/layout claim');
  checks.push('actual SCAN controller/adapter: monthly/daily views, retained min/max bands, missing cohort reason, trace/both view without requests; shared reset');
  for(const failure of ['missing-index','malformed-index','bad-bundle-hash','delayed-off']){
    const f=environment(fixture);scanAdapter(f);f.run(fs.readFileSync(path.join(base,'03_functions/js/soil_moisture_controller.js'),'utf8'));const a=f.run('createSoilMoistureController()');a.register('snotel','snotel','/snotel.json');a.register('scan','scan','/scan.json');a.sources.snotel.layer.addTo(f.map);await until(()=>a.sources.snotel.index);let release;
    f.context.fetch=async url=>{if(String(url).endsWith('/scan.json')){if(failure==='missing-index')return new Response('',{status:404});if(failure==='malformed-index')return new Response('{bad');if(failure==='delayed-off')await new Promise(r=>release=r);}if(failure==='bad-bundle-hash'&&String(url).endsWith('/scan-2191.json')){const b=fs.readFileSync(path.join(fixture,'scan-2191.json'));b[b.length-2]^=1;return new Response(b);}return f.fetcher(url);};
    a.sources.scan.layer.addTo(f.map);
    if(failure==='delayed-off'){await until(()=>!!release);f.map.removeLayer(a.sources.scan.layer);release();await new Promise(r=>setTimeout(r,5));assert.equal(a.sources.scan.index,null);assert.equal(a.sources.scan.status,'off');}
    else if(failure==='bad-bundle-hash'){await until(()=>a.sources.scan.index);a.redraw();await a.select('scan:2191:CA:SCAN');assert(f.map.popup.content.textContent.includes('hash mismatch'));assert.equal(a.stats().historyCache,0);}
    else {await until(()=>a.sources.scan.status.startsWith('unavailable:'));assert.equal(a.sources.scan.index,null);}
    assert(a.sources.snotel.index);assert(a.engine.state.enabled.snotel);assert(a.stats().markers>=3);a.reset();
  }
  checks.push('catalog-only dendra activation and metadata-only popup make no history request; missing/malformed independent source, corrupt bundle hash and delayed-off response cannot erase other source or resurrect selection');
  console.log(JSON.stringify({status:'PASS',scope:'offline actual component behavior; DOM doubles, no browser/layout acceptance',checks,snapshots},null,2));
}
module.exports={Element,environment,until,scanAdapter,UI,Charts,E,D,T,Core};
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});
