'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {Element,environment,until,scanAdapter,Charts:C,T,Core}=require('./test_soil_popup_presentation.js');
const dir=path.resolve(process.argv[2]),env=environment(dir),checks=[];scanAdapter(env);
for(const [date,year] of [['2026-09-30',2026],['2026-10-01',2027],['2026-10-02',2027]]){const now=Date.parse(date+'T12:00:00-08:00');assert.equal(C.currentWY(now),year);assert.deepEqual([...C.yearSelection([2025,2026],'current',now)],year===2026?[2026]:[]);assert.deepEqual([...C.yearSelection([2023,2024,2025,2026],'recent',now)],[2024,2025,2026]);}
assert.equal(C.currentWY(Date.parse('2026-10-01T07:59:59Z')),2026);assert.equal(C.currentWY(Date.parse('2026-10-01T08:00:00Z')),2027);
assert.deepEqual(['2024-02-28','2024-02-29','2024-03-01'].map(C.dowy),[151,152,153]);assert.deepEqual(['2026-02-28','2026-03-01'].map(C.dowy),[151,152]);assert.deepEqual(['2026-02-28','2026-03-01'].map(C.plotDay),[151,153]);checks.push('Sep30/Oct1/Oct2 ending-year rollover; fixed PST boundary; true DOWY distinct from leap-aligned plot day');
const body=JSON.parse(fs.readFileSync(path.join(dir,'scan-2191.json'))),before=JSON.stringify(body),decoded=T.decode(body,'scan','2191:CA:SCAN');env.context.scanTables=decoded.tables;const model=env.run("ptScanPresentationData('2191',8,scanTables)");assert.equal(JSON.stringify(body),before);assert.equal(model.priorTraces,0);assert(model.reference.length>=200);assert(model.referenceReason.includes('Underlying reference-year traces not included'));
for(const p of model.reference){assert.equal(p.p00,Number(p.raw.p00));assert.equal(p.p100,Number(p.raw.p100));assert(Number(p.raw.n_years)>=Number(p.raw.min_years_for_context));}
const march=model.seasonal.find(r=>r.date==='2026-03-01');assert.equal(march.dowy,152);assert.equal(march.x,152);assert.equal(march.raw.water_day,'152');checks.push('SCAN stored water_day/reference coordinate and every retained min/max/support value unchanged, no leap realignment of reference product');
const el=new Element();const state={view:'years',years:new Set([2026])};C.render(el,model,state);assert(el.querySelectorAll('[data-wy]').length);const bandHash=crypto.createHash('sha256').update(el.querySelector('[data-band="p00-p10"]').getAttribute('points')).digest('hex');el.querySelector('[data-chart-year="2026"]').click();assert.equal(el.querySelectorAll('[data-wy]').length,0);assert.equal(crypto.createHash('sha256').update(el.querySelector('[data-band="p00-p10"]').getAttribute('points')).digest('hex'),bandHash);el.querySelector('[data-chart-view="history"]').click();assert(el.textContent.includes(model.history[0].date));assert(el.textContent.includes(model.history.at(-1).date));assert(el.querySelector('[data-band="p30-p70"]'));checks.push('actual chart year filtering leaves full reference intact; history restores full acquired monthly interval and monthly band');
const blue=JSON.parse(fs.readFileSync(path.join(dir,'snotel-356.json'))),pilot=C.snotel(blue.data.data[0]);assert.equal(pilot.history[0].date,'2026-06-23');assert.equal(pilot.history.at(-1).date,'2026-09-20');assert.deepEqual([...new Set(pilot.seasonal.map(r=>r.wy))],[2026]);assert.equal(pilot.reference.length,0);assert.equal(pilot.history[0].raw.date,'2026-06-23');C.render(el,pilot,{});assert(el.querySelector('[data-band-tools]').hidden);const hit=el.querySelector('[data-chart-hit]');hit.focus();hit.dispatch('keydown',{key:'Home'});assert(el.querySelector('[data-chart-readout]').textContent.includes('2026-06-23'));assert(el.querySelector('[data-chart-readout]').textContent.includes('sampling coverage unknown'));
const synthetic=[C.row('2024-02-28',0,{}),C.row('2024-02-29',null,{},false),C.row('2024-03-01',99,{})];assert.equal(C.segments(synthetic).length,2);assert.equal(C.segments(synthetic)[0][0].v,0);const [lo,hi]=C.scale([0,99]);assert(lo<=0&&hi>=99);assert.deepEqual(C.scale([5,6],true),[0,100,20]);checks.push('SNOTEL only supplied WY, exact date-only span, keyboard readout; synthetic zero/extreme/gap scale assertions');
// Source-specific prior fallback groups are retained where actually supplied.
let fallback=null;for(const f of fs.readdirSync(dir).filter(f=>/^scan-\d+\.json$/.test(f))){const b=JSON.parse(fs.readFileSync(path.join(dir,f)));if(b.tables['scan_sms_prior_wy_fallback_traces.csv'].rows.length){fallback=b;break;}}
assert(fallback);const triplet=fallback.feature.properties.station_triplet;env.context.fallbackTables=T.decode(fallback,'scan',triplet).tables;const depth=env.context.fallbackTables['scan_sms_prior_wy_fallback_traces.csv'][0].depth_in;const fm=env.run(`ptScanPresentationData('${fallback.feature.properties.site_code}',${Number(depth)},fallbackTables)`);assert(fm.priorTraces>0);assert(fm.seasonal.some(r=>r.wy<2026));checks.push('actual available SCAN prior fallback station retains complete supplied prior traces, distinct from percentile cohort');
(async()=>{
 const retained=[];
 for(const date of ['2026-09-30','2026-10-01','2026-10-02']){
  const f=environment(dir),now=Date.parse(date+'T12:00:00-08:00');f.window.BRIM.soilMoistureCharts={...C,currentWY:()=>C.currentWY(now),currentDate:()=>C.currentDate(now),yearSelection:(years,shortcut)=>C.yearSelection(years,shortcut,now)};
  const reader=new f.window.BrimDendraReader.Reader('http://saved.invalid/dendra/index.json');await reader.loadIndex();f.context.reader=reader;const layer=f.run("makeDendraLayer({name:'dendra',reader,popupOnly:true})");layer.addTo(f.map);const sensor=reader.index.streams.find(s=>s.datastream_id==='63531a67a9b61453fa1ca4ed');layer.dendra.state.choices[sensor.station_id]=sensor.datastream_id;layer.dendra.openStation(sensor.station_id);await until(()=>f.map.popup?.content.querySelector('[data-overview] svg'));const box=f.map.popup.content;
  box.querySelector('[data-years="current"]').click();if(date!=='2026-09-30')assert.equal(box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').length,0);else assert(box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').every(p=>p.getAttribute('data-wy')==='2026'));
  box.querySelector('[data-years="all"]').click();const paths=box.querySelector('[data-seasonal]').querySelectorAll('.data-trace').filter(p=>p.getAttribute('data-wy')==='2025'),points=paths.reduce((n,p)=>n+(p.getAttribute('d').match(/[ML]/g)||[]).length,0),rows=await reader.history(reader.index,sensor);assert.equal(points,rows.filter(r=>r.wy===2025&&Core.good(r)).length);assert(points>300);const overview=box.querySelector('[data-overview]').querySelectorAll('.data-trace').reduce((n,p)=>n+(p.getAttribute('d').match(/[ML]/g)||[]).length,0);assert.equal(overview,rows.filter(Core.good).length);retained.push({date,current_wy:C.currentWY(now),prior2025Points:points,historyPoints:overview});layer.forceRemove(f.map);
 }
 assert.equal(retained[0].prior2025Points,retained[2].prior2025Points);checks.push('actual dendra component at three rollover clocks: WY2027 empty current; complete >300-point acquired WY2025 and chronological history preserved');
 console.log(JSON.stringify({status:'PASS',scope:'actual source adapters/charts with saved rows and explicit test clocks; no browser',checks,retained,fallback_station:triplet,doe_reference_days:model.reference.length,doe_monthly_rows:model.history.length},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
